// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package queryParser

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockQueryOperation creates a new instance of MockQueryOperation. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQueryOperation(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQueryOperation {
	mock := &MockQueryOperation{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockQueryOperation is an autogenerated mock type for the QueryOperation type
type MockQueryOperation struct {
	mock.Mock
}

type MockQueryOperation_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQueryOperation) EXPECT() *MockQueryOperation_Expecter {
	return &MockQueryOperation_Expecter{mock: &_m.Mock}
}

// IsQueryOperation provides a mock function for the type MockQueryOperation
func (_mock *MockQueryOperation) IsQueryOperation() {
	_mock.Called()
	return
}

// MockQueryOperation_IsQueryOperation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsQueryOperation'
type MockQueryOperation_IsQueryOperation_Call struct {
	*mock.Call
}

// IsQueryOperation is a helper method to define mock.On call
func (_e *MockQueryOperation_Expecter) IsQueryOperation() *MockQueryOperation_IsQueryOperation_Call {
	return &MockQueryOperation_IsQueryOperation_Call{Call: _e.mock.On("IsQueryOperation")}
}

func (_c *MockQueryOperation_IsQueryOperation_Call) Run(run func()) *MockQueryOperation_IsQueryOperation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockQueryOperation_IsQueryOperation_Call) Return() *MockQueryOperation_IsQueryOperation_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockQueryOperation_IsQueryOperation_Call) RunAndReturn(run func()) *MockQueryOperation_IsQueryOperation_Call {
	_c.Run(run)
	return _c
}
