// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package query

import (
	"iter"

	mock "github.com/stretchr/testify/mock"
)

// NewMockAccessPolicy creates a new instance of MockAccessPolicy. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAccessPolicy(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAccessPolicy {
	mock := &MockAccessPolicy{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAccessPolicy is an autogenerated mock type for the AccessPolicy type
type MockAccessPolicy struct {
	mock.Mock
}

type MockAccessPolicy_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAccessPolicy) EXPECT() *MockAccessPolicy_Expecter {
	return &MockAccessPolicy_Expecter{mock: &_m.Mock}
}

// GetTableAccessPolicy provides a mock function for the type MockAccessPolicy
func (_mock *MockAccessPolicy) GetTableAccessPolicy(tableName string) TableAccessPolicy {
	ret := _mock.Called(tableName)

	if len(ret) == 0 {
		panic("no return value specified for GetTableAccessPolicy")
	}

	var r0 TableAccessPolicy
	if returnFunc, ok := ret.Get(0).(func(string) TableAccessPolicy); ok {
		r0 = returnFunc(tableName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(TableAccessPolicy)
		}
	}
	return r0
}

// MockAccessPolicy_GetTableAccessPolicy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTableAccessPolicy'
type MockAccessPolicy_GetTableAccessPolicy_Call struct {
	*mock.Call
}

// GetTableAccessPolicy is a helper method to define mock.On call
//   - tableName string
func (_e *MockAccessPolicy_Expecter) GetTableAccessPolicy(tableName any) *MockAccessPolicy_GetTableAccessPolicy_Call {
	return &MockAccessPolicy_GetTableAccessPolicy_Call{Call: _e.mock.On("GetTableAccessPolicy", tableName)}
}

func (_c *MockAccessPolicy_GetTableAccessPolicy_Call) Run(run func(tableName string)) *MockAccessPolicy_GetTableAccessPolicy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAccessPolicy_GetTableAccessPolicy_Call) Return(tableAccessPolicy TableAccessPolicy) *MockAccessPolicy_GetTableAccessPolicy_Call {
	_c.Call.Return(tableAccessPolicy)
	return _c
}

func (_c *MockAccessPolicy_GetTableAccessPolicy_Call) RunAndReturn(run func(tableName string) TableAccessPolicy) *MockAccessPolicy_GetTableAccessPolicy_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTableAccessPolicy creates a new instance of MockTableAccessPolicy. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTableAccessPolicy(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTableAccessPolicy {
	mock := &MockTableAccessPolicy{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTableAccessPolicy is an autogenerated mock type for the TableAccessPolicy type
type MockTableAccessPolicy struct {
	mock.Mock
}

type MockTableAccessPolicy_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTableAccessPolicy) EXPECT() *MockTableAccessPolicy_Expecter {
	return &MockTableAccessPolicy_Expecter{mock: &_m.Mock}
}

// CanAccess provides a mock function for the type MockTableAccessPolicy
func (_mock *MockTableAccessPolicy) CanAccess() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for CanAccess")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockTableAccessPolicy_CanAccess_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CanAccess'
type MockTableAccessPolicy_CanAccess_Call struct {
	*mock.Call
}

// CanAccess is a helper method to define mock.On call
func (_e *MockTableAccessPolicy_Expecter) CanAccess() *MockTableAccessPolicy_CanAccess_Call {
	return &MockTableAccessPolicy_CanAccess_Call{Call: _e.mock.On("CanAccess")}
}

func (_c *MockTableAccessPolicy_CanAccess_Call) Run(run func()) *MockTableAccessPolicy_CanAccess_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTableAccessPolicy_CanAccess_Call) Return(b bool) *MockTableAccessPolicy_CanAccess_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockTableAccessPolicy_CanAccess_Call) RunAndReturn(run func() bool) *MockTableAccessPolicy_CanAccess_Call {
	_c.Call.Return(run)
	return _c
}

// GetColumnAccessPolicy provides a mock function for the type MockTableAccessPolicy
func (_mock *MockTableAccessPolicy) GetColumnAccessPolicy(columnName string) ColumnAccessPolicy {
	ret := _mock.Called(columnName)

	if len(ret) == 0 {
		panic("no return value specified for GetColumnAccessPolicy")
	}

	var r0 ColumnAccessPolicy
	if returnFunc, ok := ret.Get(0).(func(string) ColumnAccessPolicy); ok {
		r0 = returnFunc(columnName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ColumnAccessPolicy)
		}
	}
	return r0
}

// MockTableAccessPolicy_GetColumnAccessPolicy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetColumnAccessPolicy'
type MockTableAccessPolicy_GetColumnAccessPolicy_Call struct {
	*mock.Call
}

// GetColumnAccessPolicy is a helper method to define mock.On call
//   - columnName string
func (_e *MockTableAccessPolicy_Expecter) GetColumnAccessPolicy(columnName any) *MockTableAccessPolicy_GetColumnAccessPolicy_Call {
	return &MockTableAccessPolicy_GetColumnAccessPolicy_Call{Call: _e.mock.On("GetColumnAccessPolicy", columnName)}
}

func (_c *MockTableAccessPolicy_GetColumnAccessPolicy_Call) Run(run func(columnName string)) *MockTableAccessPolicy_GetColumnAccessPolicy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTableAccessPolicy_GetColumnAccessPolicy_Call) Return(columnAccessPolicy ColumnAccessPolicy) *MockTableAccessPolicy_GetColumnAccessPolicy_Call {
	_c.Call.Return(columnAccessPolicy)
	return _c
}

func (_c *MockTableAccessPolicy_GetColumnAccessPolicy_Call) RunAndReturn(run func(columnName string) ColumnAccessPolicy) *MockTableAccessPolicy_GetColumnAccessPolicy_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockColumnAccessPolicy creates a new instance of MockColumnAccessPolicy. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockColumnAccessPolicy(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockColumnAccessPolicy {
	mock := &MockColumnAccessPolicy{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockColumnAccessPolicy is an autogenerated mock type for the ColumnAccessPolicy type
type MockColumnAccessPolicy struct {
	mock.Mock
}

type MockColumnAccessPolicy_Expecter struct {
	mock *mock.Mock
}

func (_m *MockColumnAccessPolicy) EXPECT() *MockColumnAccessPolicy_Expecter {
	return &MockColumnAccessPolicy_Expecter{mock: &_m.Mock}
}

// CanAccess provides a mock function for the type MockColumnAccessPolicy
func (_mock *MockColumnAccessPolicy) CanAccess() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for CanAccess")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockColumnAccessPolicy_CanAccess_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CanAccess'
type MockColumnAccessPolicy_CanAccess_Call struct {
	*mock.Call
}

// CanAccess is a helper method to define mock.On call
func (_e *MockColumnAccessPolicy_Expecter) CanAccess() *MockColumnAccessPolicy_CanAccess_Call {
	return &MockColumnAccessPolicy_CanAccess_Call{Call: _e.mock.On("CanAccess")}
}

func (_c *MockColumnAccessPolicy_CanAccess_Call) Run(run func()) *MockColumnAccessPolicy_CanAccess_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockColumnAccessPolicy_CanAccess_Call) Return(b bool) *MockColumnAccessPolicy_CanAccess_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockColumnAccessPolicy_CanAccess_Call) RunAndReturn(run func() bool) *MockColumnAccessPolicy_CanAccess_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockFilterExpression creates a new instance of MockFilterExpression. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFilterExpression(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFilterExpression {
	mock := &MockFilterExpression{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFilterExpression is an autogenerated mock type for the FilterExpression type
type MockFilterExpression struct {
	mock.Mock
}

type MockFilterExpression_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFilterExpression) EXPECT() *MockFilterExpression_Expecter {
	return &MockFilterExpression_Expecter{mock: &_m.Mock}
}

// IsFilterExpression provides a mock function for the type MockFilterExpression
func (_mock *MockFilterExpression) IsFilterExpression() {
	_mock.Called()
	return
}

// MockFilterExpression_IsFilterExpression_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsFilterExpression'
type MockFilterExpression_IsFilterExpression_Call struct {
	*mock.Call
}

// IsFilterExpression is a helper method to define mock.On call
func (_e *MockFilterExpression_Expecter) IsFilterExpression() *MockFilterExpression_IsFilterExpression_Call {
	return &MockFilterExpression_IsFilterExpression_Call{Call: _e.mock.On("IsFilterExpression")}
}

func (_c *MockFilterExpression_IsFilterExpression_Call) Run(run func()) *MockFilterExpression_IsFilterExpression_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFilterExpression_IsFilterExpression_Call) Return() *MockFilterExpression_IsFilterExpression_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockFilterExpression_IsFilterExpression_Call) RunAndReturn(run func()) *MockFilterExpression_IsFilterExpression_Call {
	_c.Run(run)
	return _c
}

// NewMockValueExpression creates a new instance of MockValueExpression. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockValueExpression(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockValueExpression {
	mock := &MockValueExpression{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockValueExpression is an autogenerated mock type for the ValueExpression type
type MockValueExpression struct {
	mock.Mock
}

type MockValueExpression_Expecter struct {
	mock *mock.Mock
}

func (_m *MockValueExpression) EXPECT() *MockValueExpression_Expecter {
	return &MockValueExpression_Expecter{mock: &_m.Mock}
}

// GetTypeName provides a mock function for the type MockValueExpression
func (_mock *MockValueExpression) GetTypeName() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetTypeName")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockValueExpression_GetTypeName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTypeName'
type MockValueExpression_GetTypeName_Call struct {
	*mock.Call
}

// GetTypeName is a helper method to define mock.On call
func (_e *MockValueExpression_Expecter) GetTypeName() *MockValueExpression_GetTypeName_Call {
	return &MockValueExpression_GetTypeName_Call{Call: _e.mock.On("GetTypeName")}
}

func (_c *MockValueExpression_GetTypeName_Call) Run(run func()) *MockValueExpression_GetTypeName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockValueExpression_GetTypeName_Call) Return(s string) *MockValueExpression_GetTypeName_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockValueExpression_GetTypeName_Call) RunAndReturn(run func() string) *MockValueExpression_GetTypeName_Call {
	_c.Call.Return(run)
	return _c
}

// IsCompatibleWithComparisonOperator provides a mock function for the type MockValueExpression
func (_mock *MockValueExpression) IsCompatibleWithComparisonOperator(op ComparisonOperator) bool {
	ret := _mock.Called(op)

	if len(ret) == 0 {
		panic("no return value specified for IsCompatibleWithComparisonOperator")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(ComparisonOperator) bool); ok {
		r0 = returnFunc(op)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockValueExpression_IsCompatibleWithComparisonOperator_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsCompatibleWithComparisonOperator'
type MockValueExpression_IsCompatibleWithComparisonOperator_Call struct {
	*mock.Call
}

// IsCompatibleWithComparisonOperator is a helper method to define mock.On call
//   - op ComparisonOperator
func (_e *MockValueExpression_Expecter) IsCompatibleWithComparisonOperator(op any) *MockValueExpression_IsCompatibleWithComparisonOperator_Call {
	return &MockValueExpression_IsCompatibleWithComparisonOperator_Call{Call: _e.mock.On("IsCompatibleWithComparisonOperator", op)}
}

func (_c *MockValueExpression_IsCompatibleWithComparisonOperator_Call) Run(run func(op ComparisonOperator)) *MockValueExpression_IsCompatibleWithComparisonOperator_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 ComparisonOperator
		if args[0] != nil {
			arg0 = args[0].(ComparisonOperator)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockValueExpression_IsCompatibleWithComparisonOperator_Call) Return(b bool) *MockValueExpression_IsCompatibleWithComparisonOperator_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockValueExpression_IsCompatibleWithComparisonOperator_Call) RunAndReturn(run func(op ComparisonOperator) bool) *MockValueExpression_IsCompatibleWithComparisonOperator_Call {
	_c.Call.Return(run)
	return _c
}

// IsSupportedByDbType provides a mock function for the type MockValueExpression
func (_mock *MockValueExpression) IsSupportedByDbType(dbType DbDataTypeName) bool {
	ret := _mock.Called(dbType)

	if len(ret) == 0 {
		panic("no return value specified for IsSupportedByDbType")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(DbDataTypeName) bool); ok {
		r0 = returnFunc(dbType)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockValueExpression_IsSupportedByDbType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsSupportedByDbType'
type MockValueExpression_IsSupportedByDbType_Call struct {
	*mock.Call
}

// IsSupportedByDbType is a helper method to define mock.On call
//   - dbType DbDataTypeName
func (_e *MockValueExpression_Expecter) IsSupportedByDbType(dbType any) *MockValueExpression_IsSupportedByDbType_Call {
	return &MockValueExpression_IsSupportedByDbType_Call{Call: _e.mock.On("IsSupportedByDbType", dbType)}
}

func (_c *MockValueExpression_IsSupportedByDbType_Call) Run(run func(dbType DbDataTypeName)) *MockValueExpression_IsSupportedByDbType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 DbDataTypeName
		if args[0] != nil {
			arg0 = args[0].(DbDataTypeName)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockValueExpression_IsSupportedByDbType_Call) Return(b bool) *MockValueExpression_IsSupportedByDbType_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockValueExpression_IsSupportedByDbType_Call) RunAndReturn(run func(dbType DbDataTypeName) bool) *MockValueExpression_IsSupportedByDbType_Call {
	_c.Call.Return(run)
	return _c
}

// WriteFilterExpression provides a mock function for the type MockValueExpression
func (_mock *MockValueExpression) WriteFilterExpression(o *sqlQuery, fieldName string, op ComparisonOperator) error {
	ret := _mock.Called(o, fieldName, op)

	if len(ret) == 0 {
		panic("no return value specified for WriteFilterExpression")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*sqlQuery, string, ComparisonOperator) error); ok {
		r0 = returnFunc(o, fieldName, op)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockValueExpression_WriteFilterExpression_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteFilterExpression'
type MockValueExpression_WriteFilterExpression_Call struct {
	*mock.Call
}

// WriteFilterExpression is a helper method to define mock.On call
//   - o *sqlQuery
//   - fieldName string
//   - op ComparisonOperator
func (_e *MockValueExpression_Expecter) WriteFilterExpression(o any, fieldName any, op any) *MockValueExpression_WriteFilterExpression_Call {
	return &MockValueExpression_WriteFilterExpression_Call{Call: _e.mock.On("WriteFilterExpression", o, fieldName, op)}
}

func (_c *MockValueExpression_WriteFilterExpression_Call) Run(run func(o *sqlQuery, fieldName string, op ComparisonOperator)) *MockValueExpression_WriteFilterExpression_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *sqlQuery
		if args[0] != nil {
			arg0 = args[0].(*sqlQuery)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 ComparisonOperator
		if args[2] != nil {
			arg2 = args[2].(ComparisonOperator)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockValueExpression_WriteFilterExpression_Call) Return(err error) *MockValueExpression_WriteFilterExpression_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockValueExpression_WriteFilterExpression_Call) RunAndReturn(run func(o *sqlQuery, fieldName string, op ComparisonOperator) error) *MockValueExpression_WriteFilterExpression_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSchema creates a new instance of MockSchema. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSchema(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSchema {
	mock := &MockSchema{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSchema is an autogenerated mock type for the Schema type
type MockSchema struct {
	mock.Mock
}

type MockSchema_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSchema) EXPECT() *MockSchema_Expecter {
	return &MockSchema_Expecter{mock: &_m.Mock}
}

// GetTableMetadata provides a mock function for the type MockSchema
func (_mock *MockSchema) GetTableMetadata(tableName string) TableMetadata {
	ret := _mock.Called(tableName)

	if len(ret) == 0 {
		panic("no return value specified for GetTableMetadata")
	}

	var r0 TableMetadata
	if returnFunc, ok := ret.Get(0).(func(string) TableMetadata); ok {
		r0 = returnFunc(tableName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(TableMetadata)
		}
	}
	return r0
}

// MockSchema_GetTableMetadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTableMetadata'
type MockSchema_GetTableMetadata_Call struct {
	*mock.Call
}

// GetTableMetadata is a helper method to define mock.On call
//   - tableName string
func (_e *MockSchema_Expecter) GetTableMetadata(tableName any) *MockSchema_GetTableMetadata_Call {
	return &MockSchema_GetTableMetadata_Call{Call: _e.mock.On("GetTableMetadata", tableName)}
}

func (_c *MockSchema_GetTableMetadata_Call) Run(run func(tableName string)) *MockSchema_GetTableMetadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSchema_GetTableMetadata_Call) Return(tableMetadata TableMetadata) *MockSchema_GetTableMetadata_Call {
	_c.Call.Return(tableMetadata)
	return _c
}

func (_c *MockSchema_GetTableMetadata_Call) RunAndReturn(run func(tableName string) TableMetadata) *MockSchema_GetTableMetadata_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTableModel creates a new instance of MockTableModel. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTableModel(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTableModel {
	mock := &MockTableModel{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTableModel is an autogenerated mock type for the TableModel type
type MockTableModel struct {
	mock.Mock
}

type MockTableModel_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTableModel) EXPECT() *MockTableModel_Expecter {
	return &MockTableModel_Expecter{mock: &_m.Mock}
}

// GetJoinOnValue provides a mock function for the type MockTableModel
func (_mock *MockTableModel) GetJoinOnValue(relationshipId string) (string, error) {
	ret := _mock.Called(relationshipId)

	if len(ret) == 0 {
		panic("no return value specified for GetJoinOnValue")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(relationshipId)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(relationshipId)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(relationshipId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTableModel_GetJoinOnValue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetJoinOnValue'
type MockTableModel_GetJoinOnValue_Call struct {
	*mock.Call
}

// GetJoinOnValue is a helper method to define mock.On call
//   - relationshipId string
func (_e *MockTableModel_Expecter) GetJoinOnValue(relationshipId any) *MockTableModel_GetJoinOnValue_Call {
	return &MockTableModel_GetJoinOnValue_Call{Call: _e.mock.On("GetJoinOnValue", relationshipId)}
}

func (_c *MockTableModel_GetJoinOnValue_Call) Run(run func(relationshipId string)) *MockTableModel_GetJoinOnValue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTableModel_GetJoinOnValue_Call) Return(s string, err error) *MockTableModel_GetJoinOnValue_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockTableModel_GetJoinOnValue_Call) RunAndReturn(run func(relationshipId string) (string, error)) *MockTableModel_GetJoinOnValue_Call {
	_c.Call.Return(run)
	return _c
}

// NewSlice provides a mock function for the type MockTableModel
func (_mock *MockTableModel) NewSlice(jsonData []byte) ([]TableModel, error) {
	ret := _mock.Called(jsonData)

	if len(ret) == 0 {
		panic("no return value specified for NewSlice")
	}

	var r0 []TableModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]byte) ([]TableModel, error)); ok {
		return returnFunc(jsonData)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte) []TableModel); ok {
		r0 = returnFunc(jsonData)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]TableModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = returnFunc(jsonData)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTableModel_NewSlice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewSlice'
type MockTableModel_NewSlice_Call struct {
	*mock.Call
}

// NewSlice is a helper method to define mock.On call
//   - jsonData []byte
func (_e *MockTableModel_Expecter) NewSlice(jsonData any) *MockTableModel_NewSlice_Call {
	return &MockTableModel_NewSlice_Call{Call: _e.mock.On("NewSlice", jsonData)}
}

func (_c *MockTableModel_NewSlice_Call) Run(run func(jsonData []byte)) *MockTableModel_NewSlice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTableModel_NewSlice_Call) Return(tableModels []TableModel, err error) *MockTableModel_NewSlice_Call {
	_c.Call.Return(tableModels, err)
	return _c
}

func (_c *MockTableModel_NewSlice_Call) RunAndReturn(run func(jsonData []byte) ([]TableModel, error)) *MockTableModel_NewSlice_Call {
	_c.Call.Return(run)
	return _c
}

// SetRelationshipField provides a mock function for the type MockTableModel
func (_mock *MockTableModel) SetRelationshipField(relationshipId string, value TableModel) error {
	ret := _mock.Called(relationshipId, value)

	if len(ret) == 0 {
		panic("no return value specified for SetRelationshipField")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, TableModel) error); ok {
		r0 = returnFunc(relationshipId, value)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTableModel_SetRelationshipField_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetRelationshipField'
type MockTableModel_SetRelationshipField_Call struct {
	*mock.Call
}

// SetRelationshipField is a helper method to define mock.On call
//   - relationshipId string
//   - value TableModel
func (_e *MockTableModel_Expecter) SetRelationshipField(relationshipId any, value any) *MockTableModel_SetRelationshipField_Call {
	return &MockTableModel_SetRelationshipField_Call{Call: _e.mock.On("SetRelationshipField", relationshipId, value)}
}

func (_c *MockTableModel_SetRelationshipField_Call) Run(run func(relationshipId string, value TableModel)) *MockTableModel_SetRelationshipField_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 TableModel
		if args[1] != nil {
			arg1 = args[1].(TableModel)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTableModel_SetRelationshipField_Call) Return(err error) *MockTableModel_SetRelationshipField_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTableModel_SetRelationshipField_Call) RunAndReturn(run func(relationshipId string, value TableModel) error) *MockTableModel_SetRelationshipField_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTableMetadata creates a new instance of MockTableMetadata. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTableMetadata(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTableMetadata {
	mock := &MockTableMetadata{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTableMetadata is an autogenerated mock type for the TableMetadata type
type MockTableMetadata struct {
	mock.Mock
}

type MockTableMetadata_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTableMetadata) EXPECT() *MockTableMetadata_Expecter {
	return &MockTableMetadata_Expecter{mock: &_m.Mock}
}

// ColumnCount provides a mock function for the type MockTableMetadata
func (_mock *MockTableMetadata) ColumnCount() int {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ColumnCount")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func() int); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// MockTableMetadata_ColumnCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ColumnCount'
type MockTableMetadata_ColumnCount_Call struct {
	*mock.Call
}

// ColumnCount is a helper method to define mock.On call
func (_e *MockTableMetadata_Expecter) ColumnCount() *MockTableMetadata_ColumnCount_Call {
	return &MockTableMetadata_ColumnCount_Call{Call: _e.mock.On("ColumnCount")}
}

func (_c *MockTableMetadata_ColumnCount_Call) Run(run func()) *MockTableMetadata_ColumnCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTableMetadata_ColumnCount_Call) Return(n int) *MockTableMetadata_ColumnCount_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockTableMetadata_ColumnCount_Call) RunAndReturn(run func() int) *MockTableMetadata_ColumnCount_Call {
	_c.Call.Return(run)
	return _c
}

// Columns provides a mock function for the type MockTableMetadata
func (_mock *MockTableMetadata) Columns() iter.Seq[ColumnMetadata] {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Columns")
	}

	var r0 iter.Seq[ColumnMetadata]
	if returnFunc, ok := ret.Get(0).(func() iter.Seq[ColumnMetadata]); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(iter.Seq[ColumnMetadata])
		}
	}
	return r0
}

// MockTableMetadata_Columns_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Columns'
type MockTableMetadata_Columns_Call struct {
	*mock.Call
}

// Columns is a helper method to define mock.On call
func (_e *MockTableMetadata_Expecter) Columns() *MockTableMetadata_Columns_Call {
	return &MockTableMetadata_Columns_Call{Call: _e.mock.On("Columns")}
}

func (_c *MockTableMetadata_Columns_Call) Run(run func()) *MockTableMetadata_Columns_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTableMetadata_Columns_Call) Return(seq iter.Seq[ColumnMetadata]) *MockTableMetadata_Columns_Call {
	_c.Call.Return(seq)
	return _c
}

func (_c *MockTableMetadata_Columns_Call) RunAndReturn(run func() iter.Seq[ColumnMetadata]) *MockTableMetadata_Columns_Call {
	_c.Call.Return(run)
	return _c
}

// FullyQualifiedName provides a mock function for the type MockTableMetadata
func (_mock *MockTableMetadata) FullyQualifiedName() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for FullyQualifiedName")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockTableMetadata_FullyQualifiedName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FullyQualifiedName'
type MockTableMetadata_FullyQualifiedName_Call struct {
	*mock.Call
}

// FullyQualifiedName is a helper method to define mock.On call
func (_e *MockTableMetadata_Expecter) FullyQualifiedName() *MockTableMetadata_FullyQualifiedName_Call {
	return &MockTableMetadata_FullyQualifiedName_Call{Call: _e.mock.On("FullyQualifiedName")}
}

func (_c *MockTableMetadata_FullyQualifiedName_Call) Run(run func()) *MockTableMetadata_FullyQualifiedName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTableMetadata_FullyQualifiedName_Call) Return(s string) *MockTableMetadata_FullyQualifiedName_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockTableMetadata_FullyQualifiedName_Call) RunAndReturn(run func() string) *MockTableMetadata_FullyQualifiedName_Call {
	_c.Call.Return(run)
	return _c
}

// GetColumnMetadata provides a mock function for the type MockTableMetadata
func (_mock *MockTableMetadata) GetColumnMetadata(columnName string) ColumnMetadata {
	ret := _mock.Called(columnName)

	if len(ret) == 0 {
		panic("no return value specified for GetColumnMetadata")
	}

	var r0 ColumnMetadata
	if returnFunc, ok := ret.Get(0).(func(string) ColumnMetadata); ok {
		r0 = returnFunc(columnName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ColumnMetadata)
		}
	}
	return r0
}

// MockTableMetadata_GetColumnMetadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetColumnMetadata'
type MockTableMetadata_GetColumnMetadata_Call struct {
	*mock.Call
}

// GetColumnMetadata is a helper method to define mock.On call
//   - columnName string
func (_e *MockTableMetadata_Expecter) GetColumnMetadata(columnName any) *MockTableMetadata_GetColumnMetadata_Call {
	return &MockTableMetadata_GetColumnMetadata_Call{Call: _e.mock.On("GetColumnMetadata", columnName)}
}

func (_c *MockTableMetadata_GetColumnMetadata_Call) Run(run func(columnName string)) *MockTableMetadata_GetColumnMetadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTableMetadata_GetColumnMetadata_Call) Return(columnMetadata ColumnMetadata) *MockTableMetadata_GetColumnMetadata_Call {
	_c.Call.Return(columnMetadata)
	return _c
}

func (_c *MockTableMetadata_GetColumnMetadata_Call) RunAndReturn(run func(columnName string) ColumnMetadata) *MockTableMetadata_GetColumnMetadata_Call {
	_c.Call.Return(run)
	return _c
}

// GetModel provides a mock function for the type MockTableMetadata
func (_mock *MockTableMetadata) GetModel() TableModel {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetModel")
	}

	var r0 TableModel
	if returnFunc, ok := ret.Get(0).(func() TableModel); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(TableModel)
		}
	}
	return r0
}

// MockTableMetadata_GetModel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetModel'
type MockTableMetadata_GetModel_Call struct {
	*mock.Call
}

// GetModel is a helper method to define mock.On call
func (_e *MockTableMetadata_Expecter) GetModel() *MockTableMetadata_GetModel_Call {
	return &MockTableMetadata_GetModel_Call{Call: _e.mock.On("GetModel")}
}

func (_c *MockTableMetadata_GetModel_Call) Run(run func()) *MockTableMetadata_GetModel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTableMetadata_GetModel_Call) Return(tableModel TableModel) *MockTableMetadata_GetModel_Call {
	_c.Call.Return(tableModel)
	return _c
}

func (_c *MockTableMetadata_GetModel_Call) RunAndReturn(run func() TableModel) *MockTableMetadata_GetModel_Call {
	_c.Call.Return(run)
	return _c
}

// GetRelationshipMetadata provides a mock function for the type MockTableMetadata
func (_mock *MockTableMetadata) GetRelationshipMetadata(columnName string) RelationshipMetadata {
	ret := _mock.Called(columnName)

	if len(ret) == 0 {
		panic("no return value specified for GetRelationshipMetadata")
	}

	var r0 RelationshipMetadata
	if returnFunc, ok := ret.Get(0).(func(string) RelationshipMetadata); ok {
		r0 = returnFunc(columnName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(RelationshipMetadata)
		}
	}
	return r0
}

// MockTableMetadata_GetRelationshipMetadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRelationshipMetadata'
type MockTableMetadata_GetRelationshipMetadata_Call struct {
	*mock.Call
}

// GetRelationshipMetadata is a helper method to define mock.On call
//   - columnName string
func (_e *MockTableMetadata_Expecter) GetRelationshipMetadata(columnName any) *MockTableMetadata_GetRelationshipMetadata_Call {
	return &MockTableMetadata_GetRelationshipMetadata_Call{Call: _e.mock.On("GetRelationshipMetadata", columnName)}
}

func (_c *MockTableMetadata_GetRelationshipMetadata_Call) Run(run func(columnName string)) *MockTableMetadata_GetRelationshipMetadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTableMetadata_GetRelationshipMetadata_Call) Return(relationshipMetadata RelationshipMetadata) *MockTableMetadata_GetRelationshipMetadata_Call {
	_c.Call.Return(relationshipMetadata)
	return _c
}

func (_c *MockTableMetadata_GetRelationshipMetadata_Call) RunAndReturn(run func(columnName string) RelationshipMetadata) *MockTableMetadata_GetRelationshipMetadata_Call {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function for the type MockTableMetadata
func (_mock *MockTableMetadata) Name() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockTableMetadata_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockTableMetadata_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockTableMetadata_Expecter) Name() *MockTableMetadata_Name_Call {
	return &MockTableMetadata_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockTableMetadata_Name_Call) Run(run func()) *MockTableMetadata_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTableMetadata_Name_Call) Return(s string) *MockTableMetadata_Name_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockTableMetadata_Name_Call) RunAndReturn(run func() string) *MockTableMetadata_Name_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockColumnMetadata creates a new instance of MockColumnMetadata. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockColumnMetadata(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockColumnMetadata {
	mock := &MockColumnMetadata{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockColumnMetadata is an autogenerated mock type for the ColumnMetadata type
type MockColumnMetadata struct {
	mock.Mock
}

type MockColumnMetadata_Expecter struct {
	mock *mock.Mock
}

func (_m *MockColumnMetadata) EXPECT() *MockColumnMetadata_Expecter {
	return &MockColumnMetadata_Expecter{mock: &_m.Mock}
}

// Name provides a mock function for the type MockColumnMetadata
func (_mock *MockColumnMetadata) Name() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockColumnMetadata_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockColumnMetadata_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockColumnMetadata_Expecter) Name() *MockColumnMetadata_Name_Call {
	return &MockColumnMetadata_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockColumnMetadata_Name_Call) Run(run func()) *MockColumnMetadata_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockColumnMetadata_Name_Call) Return(s string) *MockColumnMetadata_Name_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockColumnMetadata_Name_Call) RunAndReturn(run func() string) *MockColumnMetadata_Name_Call {
	_c.Call.Return(run)
	return _c
}

// Type provides a mock function for the type MockColumnMetadata
func (_mock *MockColumnMetadata) Type() DbDataTypeName {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Type")
	}

	var r0 DbDataTypeName
	if returnFunc, ok := ret.Get(0).(func() DbDataTypeName); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(DbDataTypeName)
	}
	return r0
}

// MockColumnMetadata_Type_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Type'
type MockColumnMetadata_Type_Call struct {
	*mock.Call
}

// Type is a helper method to define mock.On call
func (_e *MockColumnMetadata_Expecter) Type() *MockColumnMetadata_Type_Call {
	return &MockColumnMetadata_Type_Call{Call: _e.mock.On("Type")}
}

func (_c *MockColumnMetadata_Type_Call) Run(run func()) *MockColumnMetadata_Type_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockColumnMetadata_Type_Call) Return(dbDataTypeName DbDataTypeName) *MockColumnMetadata_Type_Call {
	_c.Call.Return(dbDataTypeName)
	return _c
}

func (_c *MockColumnMetadata_Type_Call) RunAndReturn(run func() DbDataTypeName) *MockColumnMetadata_Type_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRelationshipMetadata creates a new instance of MockRelationshipMetadata. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRelationshipMetadata(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRelationshipMetadata {
	mock := &MockRelationshipMetadata{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRelationshipMetadata is an autogenerated mock type for the RelationshipMetadata type
type MockRelationshipMetadata struct {
	mock.Mock
}

type MockRelationshipMetadata_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRelationshipMetadata) EXPECT() *MockRelationshipMetadata_Expecter {
	return &MockRelationshipMetadata_Expecter{mock: &_m.Mock}
}

// From provides a mock function for the type MockRelationshipMetadata
func (_mock *MockRelationshipMetadata) From() TableMetadata {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for From")
	}

	var r0 TableMetadata
	if returnFunc, ok := ret.Get(0).(func() TableMetadata); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(TableMetadata)
		}
	}
	return r0
}

// MockRelationshipMetadata_From_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'From'
type MockRelationshipMetadata_From_Call struct {
	*mock.Call
}

// From is a helper method to define mock.On call
func (_e *MockRelationshipMetadata_Expecter) From() *MockRelationshipMetadata_From_Call {
	return &MockRelationshipMetadata_From_Call{Call: _e.mock.On("From")}
}

func (_c *MockRelationshipMetadata_From_Call) Run(run func()) *MockRelationshipMetadata_From_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRelationshipMetadata_From_Call) Return(tableMetadata TableMetadata) *MockRelationshipMetadata_From_Call {
	_c.Call.Return(tableMetadata)
	return _c
}

func (_c *MockRelationshipMetadata_From_Call) RunAndReturn(run func() TableMetadata) *MockRelationshipMetadata_From_Call {
	_c.Call.Return(run)
	return _c
}

// FromColumn provides a mock function for the type MockRelationshipMetadata
func (_mock *MockRelationshipMetadata) FromColumn() ColumnMetadata {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for FromColumn")
	}

	var r0 ColumnMetadata
	if returnFunc, ok := ret.Get(0).(func() ColumnMetadata); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ColumnMetadata)
		}
	}
	return r0
}

// MockRelationshipMetadata_FromColumn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FromColumn'
type MockRelationshipMetadata_FromColumn_Call struct {
	*mock.Call
}

// FromColumn is a helper method to define mock.On call
func (_e *MockRelationshipMetadata_Expecter) FromColumn() *MockRelationshipMetadata_FromColumn_Call {
	return &MockRelationshipMetadata_FromColumn_Call{Call: _e.mock.On("FromColumn")}
}

func (_c *MockRelationshipMetadata_FromColumn_Call) Run(run func()) *MockRelationshipMetadata_FromColumn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRelationshipMetadata_FromColumn_Call) Return(columnMetadata ColumnMetadata) *MockRelationshipMetadata_FromColumn_Call {
	_c.Call.Return(columnMetadata)
	return _c
}

func (_c *MockRelationshipMetadata_FromColumn_Call) RunAndReturn(run func() ColumnMetadata) *MockRelationshipMetadata_FromColumn_Call {
	_c.Call.Return(run)
	return _c
}

// Id provides a mock function for the type MockRelationshipMetadata
func (_mock *MockRelationshipMetadata) Id() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Id")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockRelationshipMetadata_Id_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Id'
type MockRelationshipMetadata_Id_Call struct {
	*mock.Call
}

// Id is a helper method to define mock.On call
func (_e *MockRelationshipMetadata_Expecter) Id() *MockRelationshipMetadata_Id_Call {
	return &MockRelationshipMetadata_Id_Call{Call: _e.mock.On("Id")}
}

func (_c *MockRelationshipMetadata_Id_Call) Run(run func()) *MockRelationshipMetadata_Id_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRelationshipMetadata_Id_Call) Return(s string) *MockRelationshipMetadata_Id_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockRelationshipMetadata_Id_Call) RunAndReturn(run func() string) *MockRelationshipMetadata_Id_Call {
	_c.Call.Return(run)
	return _c
}

// To provides a mock function for the type MockRelationshipMetadata
func (_mock *MockRelationshipMetadata) To() TableMetadata {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for To")
	}

	var r0 TableMetadata
	if returnFunc, ok := ret.Get(0).(func() TableMetadata); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(TableMetadata)
		}
	}
	return r0
}

// MockRelationshipMetadata_To_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'To'
type MockRelationshipMetadata_To_Call struct {
	*mock.Call
}

// To is a helper method to define mock.On call
func (_e *MockRelationshipMetadata_Expecter) To() *MockRelationshipMetadata_To_Call {
	return &MockRelationshipMetadata_To_Call{Call: _e.mock.On("To")}
}

func (_c *MockRelationshipMetadata_To_Call) Run(run func()) *MockRelationshipMetadata_To_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRelationshipMetadata_To_Call) Return(tableMetadata TableMetadata) *MockRelationshipMetadata_To_Call {
	_c.Call.Return(tableMetadata)
	return _c
}

func (_c *MockRelationshipMetadata_To_Call) RunAndReturn(run func() TableMetadata) *MockRelationshipMetadata_To_Call {
	_c.Call.Return(run)
	return _c
}

// ToColumn provides a mock function for the type MockRelationshipMetadata
func (_mock *MockRelationshipMetadata) ToColumn() ColumnMetadata {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ToColumn")
	}

	var r0 ColumnMetadata
	if returnFunc, ok := ret.Get(0).(func() ColumnMetadata); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ColumnMetadata)
		}
	}
	return r0
}

// MockRelationshipMetadata_ToColumn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ToColumn'
type MockRelationshipMetadata_ToColumn_Call struct {
	*mock.Call
}

// ToColumn is a helper method to define mock.On call
func (_e *MockRelationshipMetadata_Expecter) ToColumn() *MockRelationshipMetadata_ToColumn_Call {
	return &MockRelationshipMetadata_ToColumn_Call{Call: _e.mock.On("ToColumn")}
}

func (_c *MockRelationshipMetadata_ToColumn_Call) Run(run func()) *MockRelationshipMetadata_ToColumn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRelationshipMetadata_ToColumn_Call) Return(columnMetadata ColumnMetadata) *MockRelationshipMetadata_ToColumn_Call {
	_c.Call.Return(columnMetadata)
	return _c
}

func (_c *MockRelationshipMetadata_ToColumn_Call) RunAndReturn(run func() ColumnMetadata) *MockRelationshipMetadata_ToColumn_Call {
	_c.Call.Return(run)
	return _c
}

// Type provides a mock function for the type MockRelationshipMetadata
func (_mock *MockRelationshipMetadata) Type() RelationshipType {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Type")
	}

	var r0 RelationshipType
	if returnFunc, ok := ret.Get(0).(func() RelationshipType); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(RelationshipType)
	}
	return r0
}

// MockRelationshipMetadata_Type_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Type'
type MockRelationshipMetadata_Type_Call struct {
	*mock.Call
}

// Type is a helper method to define mock.On call
func (_e *MockRelationshipMetadata_Expecter) Type() *MockRelationshipMetadata_Type_Call {
	return &MockRelationshipMetadata_Type_Call{Call: _e.mock.On("Type")}
}

func (_c *MockRelationshipMetadata_Type_Call) Run(run func()) *MockRelationshipMetadata_Type_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRelationshipMetadata_Type_Call) Return(relationshipType RelationshipType) *MockRelationshipMetadata_Type_Call {
	_c.Call.Return(relationshipType)
	return _c
}

func (_c *MockRelationshipMetadata_Type_Call) RunAndReturn(run func() RelationshipType) *MockRelationshipMetadata_Type_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockQueryOperation creates a new instance of MockQueryOperation. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQueryOperation(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQueryOperation {
	mock := &MockQueryOperation{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockQueryOperation is an autogenerated mock type for the QueryOperation type
type MockQueryOperation struct {
	mock.Mock
}

type MockQueryOperation_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQueryOperation) EXPECT() *MockQueryOperation_Expecter {
	return &MockQueryOperation_Expecter{mock: &_m.Mock}
}

// IsQueryOperation provides a mock function for the type MockQueryOperation
func (_mock *MockQueryOperation) IsQueryOperation() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsQueryOperation")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockQueryOperation_IsQueryOperation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsQueryOperation'
type MockQueryOperation_IsQueryOperation_Call struct {
	*mock.Call
}

// IsQueryOperation is a helper method to define mock.On call
func (_e *MockQueryOperation_Expecter) IsQueryOperation() *MockQueryOperation_IsQueryOperation_Call {
	return &MockQueryOperation_IsQueryOperation_Call{Call: _e.mock.On("IsQueryOperation")}
}

func (_c *MockQueryOperation_IsQueryOperation_Call) Run(run func()) *MockQueryOperation_IsQueryOperation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockQueryOperation_IsQueryOperation_Call) Return(b bool) *MockQueryOperation_IsQueryOperation_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockQueryOperation_IsQueryOperation_Call) RunAndReturn(run func() bool) *MockQueryOperation_IsQueryOperation_Call {
	_c.Call.Return(run)
	return _c
}
