// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package query

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/turnerbenjamin/heterogen_portal/internal/query/queryModel"
)

// NewMockQueryExecutor creates a new instance of MockQueryExecutor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQueryExecutor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQueryExecutor {
	mock := &MockQueryExecutor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockQueryExecutor is an autogenerated mock type for the QueryExecutor type
type MockQueryExecutor struct {
	mock.Mock
}

type MockQueryExecutor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQueryExecutor) EXPECT() *MockQueryExecutor_Expecter {
	return &MockQueryExecutor_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type MockQueryExecutor
func (_mock *MockQueryExecutor) Execute(ctx context.Context, resourceName string, queryString string) (queryModel.ExecuteResult, error) {
	ret := _mock.Called(ctx, resourceName, queryString)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 queryModel.ExecuteResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (queryModel.ExecuteResult, error)); ok {
		return returnFunc(ctx, resourceName, queryString)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) queryModel.ExecuteResult); ok {
		r0 = returnFunc(ctx, resourceName, queryString)
	} else {
		r0 = ret.Get(0).(queryModel.ExecuteResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, resourceName, queryString)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQueryExecutor_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockQueryExecutor_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - resourceName string
//   - queryString string
func (_e *MockQueryExecutor_Expecter) Execute(ctx any, resourceName any, queryString any) *MockQueryExecutor_Execute_Call {
	return &MockQueryExecutor_Execute_Call{Call: _e.mock.On("Execute", ctx, resourceName, queryString)}
}

func (_c *MockQueryExecutor_Execute_Call) Run(run func(ctx context.Context, resourceName string, queryString string)) *MockQueryExecutor_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockQueryExecutor_Execute_Call) Return(executeResult queryModel.ExecuteResult, err error) *MockQueryExecutor_Execute_Call {
	_c.Call.Return(executeResult, err)
	return _c
}

func (_c *MockQueryExecutor_Execute_Call) RunAndReturn(run func(ctx context.Context, resourceName string, queryString string) (queryModel.ExecuteResult, error)) *MockQueryExecutor_Execute_Call {
	_c.Call.Return(run)
	return _c
}
