// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package query

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/turnerbenjamin/heterogen_portal/internal/query/queryDataStore"
	"github.com/turnerbenjamin/heterogen_portal/internal/query/queryModel"
)

// NewMockPayloadSigner creates a new instance of MockPayloadSigner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPayloadSigner(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPayloadSigner {
	mock := &MockPayloadSigner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPayloadSigner is an autogenerated mock type for the PayloadSigner type
type MockPayloadSigner struct {
	mock.Mock
}

type MockPayloadSigner_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPayloadSigner) EXPECT() *MockPayloadSigner_Expecter {
	return &MockPayloadSigner_Expecter{mock: &_m.Mock}
}

// Sign provides a mock function for the type MockPayloadSigner
func (_mock *MockPayloadSigner) Sign(secret []byte, data []byte) string {
	ret := _mock.Called(secret, data)

	if len(ret) == 0 {
		panic("no return value specified for Sign")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func([]byte, []byte) string); ok {
		r0 = returnFunc(secret, data)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockPayloadSigner_Sign_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Sign'
type MockPayloadSigner_Sign_Call struct {
	*mock.Call
}

// Sign is a helper method to define mock.On call
//   - secret []byte
//   - data []byte
func (_e *MockPayloadSigner_Expecter) Sign(secret any, data any) *MockPayloadSigner_Sign_Call {
	return &MockPayloadSigner_Sign_Call{Call: _e.mock.On("Sign", secret, data)}
}

func (_c *MockPayloadSigner_Sign_Call) Run(run func(secret []byte, data []byte)) *MockPayloadSigner_Sign_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPayloadSigner_Sign_Call) Return(s string) *MockPayloadSigner_Sign_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockPayloadSigner_Sign_Call) RunAndReturn(run func(secret []byte, data []byte) string) *MockPayloadSigner_Sign_Call {
	_c.Call.Return(run)
	return _c
}

// Verify provides a mock function for the type MockPayloadSigner
func (_mock *MockPayloadSigner) Verify(secret []byte, value string) ([]byte, bool) {
	ret := _mock.Called(secret, value)

	if len(ret) == 0 {
		panic("no return value specified for Verify")
	}

	var r0 []byte
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func([]byte, string) ([]byte, bool)); ok {
		return returnFunc(secret, value)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte, string) []byte); ok {
		r0 = returnFunc(secret, value)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]byte, string) bool); ok {
		r1 = returnFunc(secret, value)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// MockPayloadSigner_Verify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Verify'
type MockPayloadSigner_Verify_Call struct {
	*mock.Call
}

// Verify is a helper method to define mock.On call
//   - secret []byte
//   - value string
func (_e *MockPayloadSigner_Expecter) Verify(secret any, value any) *MockPayloadSigner_Verify_Call {
	return &MockPayloadSigner_Verify_Call{Call: _e.mock.On("Verify", secret, value)}
}

func (_c *MockPayloadSigner_Verify_Call) Run(run func(secret []byte, value string)) *MockPayloadSigner_Verify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPayloadSigner_Verify_Call) Return(data []byte, ok bool) *MockPayloadSigner_Verify_Call {
	_c.Call.Return(data, ok)
	return _c
}

func (_c *MockPayloadSigner_Verify_Call) RunAndReturn(run func(secret []byte, value string) ([]byte, bool)) *MockPayloadSigner_Verify_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockQueryParser creates a new instance of MockQueryParser. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQueryParser(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQueryParser {
	mock := &MockQueryParser{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockQueryParser is an autogenerated mock type for the QueryParser type
type MockQueryParser struct {
	mock.Mock
}

type MockQueryParser_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQueryParser) EXPECT() *MockQueryParser_Expecter {
	return &MockQueryParser_Expecter{mock: &_m.Mock}
}

// Parse provides a mock function for the type MockQueryParser
func (_mock *MockQueryParser) Parse(queryString string, queryDataStore1 queryDataStore.QueryDataStore) error {
	ret := _mock.Called(queryString, queryDataStore1)

	if len(ret) == 0 {
		panic("no return value specified for Parse")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, queryDataStore.QueryDataStore) error); ok {
		r0 = returnFunc(queryString, queryDataStore1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockQueryParser_Parse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Parse'
type MockQueryParser_Parse_Call struct {
	*mock.Call
}

// Parse is a helper method to define mock.On call
//   - queryString string
//   - queryDataStore1 queryDataStore.QueryDataStore
func (_e *MockQueryParser_Expecter) Parse(queryString any, queryDataStore1 any) *MockQueryParser_Parse_Call {
	return &MockQueryParser_Parse_Call{Call: _e.mock.On("Parse", queryString, queryDataStore1)}
}

func (_c *MockQueryParser_Parse_Call) Run(run func(queryString string, queryDataStore1 queryDataStore.QueryDataStore)) *MockQueryParser_Parse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 queryDataStore.QueryDataStore
		if args[1] != nil {
			arg1 = args[1].(queryDataStore.QueryDataStore)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQueryParser_Parse_Call) Return(err error) *MockQueryParser_Parse_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockQueryParser_Parse_Call) RunAndReturn(run func(queryString string, queryDataStore1 queryDataStore.QueryDataStore) error) *MockQueryParser_Parse_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockQueryExecutor creates a new instance of MockQueryExecutor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQueryExecutor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQueryExecutor {
	mock := &MockQueryExecutor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockQueryExecutor is an autogenerated mock type for the QueryExecutor type
type MockQueryExecutor struct {
	mock.Mock
}

type MockQueryExecutor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQueryExecutor) EXPECT() *MockQueryExecutor_Expecter {
	return &MockQueryExecutor_Expecter{mock: &_m.Mock}
}

// ExecuteJsonRequest provides a mock function for the type MockQueryExecutor
func (_mock *MockQueryExecutor) ExecuteJsonRequest(ctx context.Context, queryStatementSty string, args []any) ([]byte, error) {
	ret := _mock.Called(ctx, queryStatementSty, args)

	if len(ret) == 0 {
		panic("no return value specified for ExecuteJsonRequest")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []any) ([]byte, error)); ok {
		return returnFunc(ctx, queryStatementSty, args)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []any) []byte); ok {
		r0 = returnFunc(ctx, queryStatementSty, args)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, []any) error); ok {
		r1 = returnFunc(ctx, queryStatementSty, args)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQueryExecutor_ExecuteJsonRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecuteJsonRequest'
type MockQueryExecutor_ExecuteJsonRequest_Call struct {
	*mock.Call
}

// ExecuteJsonRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - queryStatementSty string
//   - args []any
func (_e *MockQueryExecutor_Expecter) ExecuteJsonRequest(ctx any, queryStatementSty any, args any) *MockQueryExecutor_ExecuteJsonRequest_Call {
	return &MockQueryExecutor_ExecuteJsonRequest_Call{Call: _e.mock.On("ExecuteJsonRequest", ctx, queryStatementSty, args)}
}

func (_c *MockQueryExecutor_ExecuteJsonRequest_Call) Run(run func(ctx context.Context, queryStatementSty string, args []any)) *MockQueryExecutor_ExecuteJsonRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []any
		if args[2] != nil {
			arg2 = args[2].([]any)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockQueryExecutor_ExecuteJsonRequest_Call) Return(bytes []byte, err error) *MockQueryExecutor_ExecuteJsonRequest_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockQueryExecutor_ExecuteJsonRequest_Call) RunAndReturn(run func(ctx context.Context, queryStatementSty string, args []any) ([]byte, error)) *MockQueryExecutor_ExecuteJsonRequest_Call {
	_c.Call.Return(run)
	return _c
}

// ExecuteJsonRequestWithCount provides a mock function for the type MockQueryExecutor
func (_mock *MockQueryExecutor) ExecuteJsonRequestWithCount(ctx context.Context, queryStatementStr string, countStatementStr string, sharedArgs []any) ([]byte, *int64, error) {
	ret := _mock.Called(ctx, queryStatementStr, countStatementStr, sharedArgs)

	if len(ret) == 0 {
		panic("no return value specified for ExecuteJsonRequestWithCount")
	}

	var r0 []byte
	var r1 *int64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, []any) ([]byte, *int64, error)); ok {
		return returnFunc(ctx, queryStatementStr, countStatementStr, sharedArgs)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, []any) []byte); ok {
		r0 = returnFunc(ctx, queryStatementStr, countStatementStr, sharedArgs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, []any) *int64); ok {
		r1 = returnFunc(ctx, queryStatementStr, countStatementStr, sharedArgs)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*int64)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string, []any) error); ok {
		r2 = returnFunc(ctx, queryStatementStr, countStatementStr, sharedArgs)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockQueryExecutor_ExecuteJsonRequestWithCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecuteJsonRequestWithCount'
type MockQueryExecutor_ExecuteJsonRequestWithCount_Call struct {
	*mock.Call
}

// ExecuteJsonRequestWithCount is a helper method to define mock.On call
//   - ctx context.Context
//   - queryStatementStr string
//   - countStatementStr string
//   - sharedArgs []any
func (_e *MockQueryExecutor_Expecter) ExecuteJsonRequestWithCount(ctx any, queryStatementStr any, countStatementStr any, sharedArgs any) *MockQueryExecutor_ExecuteJsonRequestWithCount_Call {
	return &MockQueryExecutor_ExecuteJsonRequestWithCount_Call{Call: _e.mock.On("ExecuteJsonRequestWithCount", ctx, queryStatementStr, countStatementStr, sharedArgs)}
}

func (_c *MockQueryExecutor_ExecuteJsonRequestWithCount_Call) Run(run func(ctx context.Context, queryStatementStr string, countStatementStr string, sharedArgs []any)) *MockQueryExecutor_ExecuteJsonRequestWithCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []any
		if args[3] != nil {
			arg3 = args[3].([]any)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockQueryExecutor_ExecuteJsonRequestWithCount_Call) Return(bytes []byte, n *int64, err error) *MockQueryExecutor_ExecuteJsonRequestWithCount_Call {
	_c.Call.Return(bytes, n, err)
	return _c
}

func (_c *MockQueryExecutor_ExecuteJsonRequestWithCount_Call) RunAndReturn(run func(ctx context.Context, queryStatementStr string, countStatementStr string, sharedArgs []any) ([]byte, *int64, error)) *MockQueryExecutor_ExecuteJsonRequestWithCount_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPagingTokenBuilder creates a new instance of MockPagingTokenBuilder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPagingTokenBuilder(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPagingTokenBuilder {
	mock := &MockPagingTokenBuilder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPagingTokenBuilder is an autogenerated mock type for the PagingTokenBuilder type
type MockPagingTokenBuilder struct {
	mock.Mock
}

type MockPagingTokenBuilder_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPagingTokenBuilder) EXPECT() *MockPagingTokenBuilder_Expecter {
	return &MockPagingTokenBuilder_Expecter{mock: &_m.Mock}
}

// BuildToken provides a mock function for the type MockPagingTokenBuilder
func (_mock *MockPagingTokenBuilder) BuildToken(queryDataStore1 queryDataStore.QueryDataStore, lastRecord queryModel.TableModel) (string, error) {
	ret := _mock.Called(queryDataStore1, lastRecord)

	if len(ret) == 0 {
		panic("no return value specified for BuildToken")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(queryDataStore.QueryDataStore, queryModel.TableModel) (string, error)); ok {
		return returnFunc(queryDataStore1, lastRecord)
	}
	if returnFunc, ok := ret.Get(0).(func(queryDataStore.QueryDataStore, queryModel.TableModel) string); ok {
		r0 = returnFunc(queryDataStore1, lastRecord)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(queryDataStore.QueryDataStore, queryModel.TableModel) error); ok {
		r1 = returnFunc(queryDataStore1, lastRecord)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPagingTokenBuilder_BuildToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BuildToken'
type MockPagingTokenBuilder_BuildToken_Call struct {
	*mock.Call
}

// BuildToken is a helper method to define mock.On call
//   - queryDataStore1 queryDataStore.QueryDataStore
//   - lastRecord queryModel.TableModel
func (_e *MockPagingTokenBuilder_Expecter) BuildToken(queryDataStore1 any, lastRecord any) *MockPagingTokenBuilder_BuildToken_Call {
	return &MockPagingTokenBuilder_BuildToken_Call{Call: _e.mock.On("BuildToken", queryDataStore1, lastRecord)}
}

func (_c *MockPagingTokenBuilder_BuildToken_Call) Run(run func(queryDataStore1 queryDataStore.QueryDataStore, lastRecord queryModel.TableModel)) *MockPagingTokenBuilder_BuildToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 queryDataStore.QueryDataStore
		if args[0] != nil {
			arg0 = args[0].(queryDataStore.QueryDataStore)
		}
		var arg1 queryModel.TableModel
		if args[1] != nil {
			arg1 = args[1].(queryModel.TableModel)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPagingTokenBuilder_BuildToken_Call) Return(s string, err error) *MockPagingTokenBuilder_BuildToken_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockPagingTokenBuilder_BuildToken_Call) RunAndReturn(run func(queryDataStore1 queryDataStore.QueryDataStore, lastRecord queryModel.TableModel) (string, error)) *MockPagingTokenBuilder_BuildToken_Call {
	_c.Call.Return(run)
	return _c
}

// ParseToken provides a mock function for the type MockPagingTokenBuilder
func (_mock *MockPagingTokenBuilder) ParseToken(token string) (*pagingToken, error) {
	ret := _mock.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for ParseToken")
	}

	var r0 *pagingToken
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*pagingToken, error)); ok {
		return returnFunc(token)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *pagingToken); ok {
		r0 = returnFunc(token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pagingToken)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPagingTokenBuilder_ParseToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ParseToken'
type MockPagingTokenBuilder_ParseToken_Call struct {
	*mock.Call
}

// ParseToken is a helper method to define mock.On call
//   - token string
func (_e *MockPagingTokenBuilder_Expecter) ParseToken(token any) *MockPagingTokenBuilder_ParseToken_Call {
	return &MockPagingTokenBuilder_ParseToken_Call{Call: _e.mock.On("ParseToken", token)}
}

func (_c *MockPagingTokenBuilder_ParseToken_Call) Run(run func(token string)) *MockPagingTokenBuilder_ParseToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPagingTokenBuilder_ParseToken_Call) Return(pagingTokenMoqParam *pagingToken, err error) *MockPagingTokenBuilder_ParseToken_Call {
	_c.Call.Return(pagingTokenMoqParam, err)
	return _c
}

func (_c *MockPagingTokenBuilder_ParseToken_Call) RunAndReturn(run func(token string) (*pagingToken, error)) *MockPagingTokenBuilder_ParseToken_Call {
	_c.Call.Return(run)
	return _c
}
