// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package services

import (
	"context"

	"github.com/coreos/go-oidc/v3/oidc"
	"github.com/golang-jwt/jwt/v5"
	mock "github.com/stretchr/testify/mock"
	"github.com/turnerbenjamin/heterogen_portal/internal/db"
	"golang.org/x/oauth2"
)

// NewMockUserRepo creates a new instance of MockUserRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserRepo {
	mock := &MockUserRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserRepo is an autogenerated mock type for the UserRepo type
type MockUserRepo struct {
	mock.Mock
}

type MockUserRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserRepo) EXPECT() *MockUserRepo_Expecter {
	return &MockUserRepo_Expecter{mock: &_m.Mock}
}

// RetrieveUserById provides a mock function for the type MockUserRepo
func (_mock *MockUserRepo) RetrieveUserById(id string) (*db.User, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for RetrieveUserById")
	}

	var r0 *db.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*db.User, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *db.User); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepo_RetrieveUserById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RetrieveUserById'
type MockUserRepo_RetrieveUserById_Call struct {
	*mock.Call
}

// RetrieveUserById is a helper method to define mock.On call
//   - id string
func (_e *MockUserRepo_Expecter) RetrieveUserById(id any) *MockUserRepo_RetrieveUserById_Call {
	return &MockUserRepo_RetrieveUserById_Call{Call: _e.mock.On("RetrieveUserById", id)}
}

func (_c *MockUserRepo_RetrieveUserById_Call) Run(run func(id string)) *MockUserRepo_RetrieveUserById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUserRepo_RetrieveUserById_Call) Return(user *db.User, err error) *MockUserRepo_RetrieveUserById_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserRepo_RetrieveUserById_Call) RunAndReturn(run func(id string) (*db.User, error)) *MockUserRepo_RetrieveUserById_Call {
	_c.Call.Return(run)
	return _c
}

// RetrieveUserByOid provides a mock function for the type MockUserRepo
func (_mock *MockUserRepo) RetrieveUserByOid(id string) (*db.User, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for RetrieveUserByOid")
	}

	var r0 *db.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*db.User, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *db.User); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepo_RetrieveUserByOid_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RetrieveUserByOid'
type MockUserRepo_RetrieveUserByOid_Call struct {
	*mock.Call
}

// RetrieveUserByOid is a helper method to define mock.On call
//   - id string
func (_e *MockUserRepo_Expecter) RetrieveUserByOid(id any) *MockUserRepo_RetrieveUserByOid_Call {
	return &MockUserRepo_RetrieveUserByOid_Call{Call: _e.mock.On("RetrieveUserByOid", id)}
}

func (_c *MockUserRepo_RetrieveUserByOid_Call) Run(run func(id string)) *MockUserRepo_RetrieveUserByOid_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUserRepo_RetrieveUserByOid_Call) Return(user *db.User, err error) *MockUserRepo_RetrieveUserByOid_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserRepo_RetrieveUserByOid_Call) RunAndReturn(run func(id string) (*db.User, error)) *MockUserRepo_RetrieveUserByOid_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertUser provides a mock function for the type MockUserRepo
func (_mock *MockUserRepo) UpsertUser(oid string, givenName string, familyName string, userName string, emailAddress string) (*db.User, error) {
	ret := _mock.Called(oid, givenName, familyName, userName, emailAddress)

	if len(ret) == 0 {
		panic("no return value specified for UpsertUser")
	}

	var r0 *db.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string, string, string, string) (*db.User, error)); ok {
		return returnFunc(oid, givenName, familyName, userName, emailAddress)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, string, string, string) *db.User); ok {
		r0 = returnFunc(oid, givenName, familyName, userName, emailAddress)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, string, string, string) error); ok {
		r1 = returnFunc(oid, givenName, familyName, userName, emailAddress)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepo_UpsertUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertUser'
type MockUserRepo_UpsertUser_Call struct {
	*mock.Call
}

// UpsertUser is a helper method to define mock.On call
//   - oid string
//   - givenName string
//   - familyName string
//   - userName string
//   - emailAddress string
func (_e *MockUserRepo_Expecter) UpsertUser(oid any, givenName any, familyName any, userName any, emailAddress any) *MockUserRepo_UpsertUser_Call {
	return &MockUserRepo_UpsertUser_Call{Call: _e.mock.On("UpsertUser", oid, givenName, familyName, userName, emailAddress)}
}

func (_c *MockUserRepo_UpsertUser_Call) Run(run func(oid string, givenName string, familyName string, userName string, emailAddress string)) *MockUserRepo_UpsertUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockUserRepo_UpsertUser_Call) Return(user *db.User, err error) *MockUserRepo_UpsertUser_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserRepo_UpsertUser_Call) RunAndReturn(run func(oid string, givenName string, familyName string, userName string, emailAddress string) (*db.User, error)) *MockUserRepo_UpsertUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockJwtSigner creates a new instance of MockJwtSigner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockJwtSigner(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockJwtSigner {
	mock := &MockJwtSigner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockJwtSigner is an autogenerated mock type for the JwtSigner type
type MockJwtSigner struct {
	mock.Mock
}

type MockJwtSigner_Expecter struct {
	mock *mock.Mock
}

func (_m *MockJwtSigner) EXPECT() *MockJwtSigner_Expecter {
	return &MockJwtSigner_Expecter{mock: &_m.Mock}
}

// ParseWithClaims provides a mock function for the type MockJwtSigner
func (_mock *MockJwtSigner) ParseWithClaims(tokenString string, claims jwt.Claims, keyFunc jwt.Keyfunc, parserOptions ...jwt.ParserOption) (*jwt.Token, error) {
	var tmpRet mock.Arguments
	if len(parserOptions) > 0 {
		tmpRet = _mock.Called(tokenString, claims, keyFunc, parserOptions)
	} else {
		tmpRet = _mock.Called(tokenString, claims, keyFunc)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for ParseWithClaims")
	}

	var r0 *jwt.Token
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, jwt.Claims, jwt.Keyfunc, ...jwt.ParserOption) (*jwt.Token, error)); ok {
		return returnFunc(tokenString, claims, keyFunc, parserOptions...)
	}
	if returnFunc, ok := ret.Get(0).(func(string, jwt.Claims, jwt.Keyfunc, ...jwt.ParserOption) *jwt.Token); ok {
		r0 = returnFunc(tokenString, claims, keyFunc, parserOptions...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*jwt.Token)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, jwt.Claims, jwt.Keyfunc, ...jwt.ParserOption) error); ok {
		r1 = returnFunc(tokenString, claims, keyFunc, parserOptions...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockJwtSigner_ParseWithClaims_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ParseWithClaims'
type MockJwtSigner_ParseWithClaims_Call struct {
	*mock.Call
}

// ParseWithClaims is a helper method to define mock.On call
//   - tokenString string
//   - claims jwt.Claims
//   - keyFunc jwt.Keyfunc
//   - parserOptions ...jwt.ParserOption
func (_e *MockJwtSigner_Expecter) ParseWithClaims(tokenString any, claims any, keyFunc any, parserOptions ...any) *MockJwtSigner_ParseWithClaims_Call {
	return &MockJwtSigner_ParseWithClaims_Call{Call: _e.mock.On("ParseWithClaims",
		append([]any{tokenString, claims, keyFunc}, parserOptions...)...)}
}

func (_c *MockJwtSigner_ParseWithClaims_Call) Run(run func(tokenString string, claims jwt.Claims, keyFunc jwt.Keyfunc, parserOptions ...jwt.ParserOption)) *MockJwtSigner_ParseWithClaims_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 jwt.Claims
		if args[1] != nil {
			arg1 = args[1].(jwt.Claims)
		}
		var arg2 jwt.Keyfunc
		if args[2] != nil {
			arg2 = args[2].(jwt.Keyfunc)
		}
		var arg3 []jwt.ParserOption
		var variadicArgs []jwt.ParserOption
		if len(args) > 3 {
			variadicArgs = args[3].([]jwt.ParserOption)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *MockJwtSigner_ParseWithClaims_Call) Return(token *jwt.Token, err error) *MockJwtSigner_ParseWithClaims_Call {
	_c.Call.Return(token, err)
	return _c
}

func (_c *MockJwtSigner_ParseWithClaims_Call) RunAndReturn(run func(tokenString string, claims jwt.Claims, keyFunc jwt.Keyfunc, parserOptions ...jwt.ParserOption) (*jwt.Token, error)) *MockJwtSigner_ParseWithClaims_Call {
	_c.Call.Return(run)
	return _c
}

// Sign provides a mock function for the type MockJwtSigner
func (_mock *MockJwtSigner) Sign(token *jwt.Token, privateKey []byte) (string, error) {
	ret := _mock.Called(token, privateKey)

	if len(ret) == 0 {
		panic("no return value specified for Sign")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*jwt.Token, []byte) (string, error)); ok {
		return returnFunc(token, privateKey)
	}
	if returnFunc, ok := ret.Get(0).(func(*jwt.Token, []byte) string); ok {
		r0 = returnFunc(token, privateKey)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(*jwt.Token, []byte) error); ok {
		r1 = returnFunc(token, privateKey)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockJwtSigner_Sign_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Sign'
type MockJwtSigner_Sign_Call struct {
	*mock.Call
}

// Sign is a helper method to define mock.On call
//   - token *jwt.Token
//   - privateKey []byte
func (_e *MockJwtSigner_Expecter) Sign(token any, privateKey any) *MockJwtSigner_Sign_Call {
	return &MockJwtSigner_Sign_Call{Call: _e.mock.On("Sign", token, privateKey)}
}

func (_c *MockJwtSigner_Sign_Call) Run(run func(token *jwt.Token, privateKey []byte)) *MockJwtSigner_Sign_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *jwt.Token
		if args[0] != nil {
			arg0 = args[0].(*jwt.Token)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockJwtSigner_Sign_Call) Return(s string, err error) *MockJwtSigner_Sign_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockJwtSigner_Sign_Call) RunAndReturn(run func(token *jwt.Token, privateKey []byte) (string, error)) *MockJwtSigner_Sign_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPayloadSigner creates a new instance of MockPayloadSigner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPayloadSigner(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPayloadSigner {
	mock := &MockPayloadSigner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPayloadSigner is an autogenerated mock type for the PayloadSigner type
type MockPayloadSigner struct {
	mock.Mock
}

type MockPayloadSigner_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPayloadSigner) EXPECT() *MockPayloadSigner_Expecter {
	return &MockPayloadSigner_Expecter{mock: &_m.Mock}
}

// Sign provides a mock function for the type MockPayloadSigner
func (_mock *MockPayloadSigner) Sign(secret []byte, data []byte) string {
	ret := _mock.Called(secret, data)

	if len(ret) == 0 {
		panic("no return value specified for Sign")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func([]byte, []byte) string); ok {
		r0 = returnFunc(secret, data)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockPayloadSigner_Sign_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Sign'
type MockPayloadSigner_Sign_Call struct {
	*mock.Call
}

// Sign is a helper method to define mock.On call
//   - secret []byte
//   - data []byte
func (_e *MockPayloadSigner_Expecter) Sign(secret any, data any) *MockPayloadSigner_Sign_Call {
	return &MockPayloadSigner_Sign_Call{Call: _e.mock.On("Sign", secret, data)}
}

func (_c *MockPayloadSigner_Sign_Call) Run(run func(secret []byte, data []byte)) *MockPayloadSigner_Sign_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPayloadSigner_Sign_Call) Return(signedData string) *MockPayloadSigner_Sign_Call {
	_c.Call.Return(signedData)
	return _c
}

func (_c *MockPayloadSigner_Sign_Call) RunAndReturn(run func(secret []byte, data []byte) string) *MockPayloadSigner_Sign_Call {
	_c.Call.Return(run)
	return _c
}

// Verify provides a mock function for the type MockPayloadSigner
func (_mock *MockPayloadSigner) Verify(secret []byte, value string) ([]byte, bool) {
	ret := _mock.Called(secret, value)

	if len(ret) == 0 {
		panic("no return value specified for Verify")
	}

	var r0 []byte
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func([]byte, string) ([]byte, bool)); ok {
		return returnFunc(secret, value)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte, string) []byte); ok {
		r0 = returnFunc(secret, value)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]byte, string) bool); ok {
		r1 = returnFunc(secret, value)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// MockPayloadSigner_Verify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Verify'
type MockPayloadSigner_Verify_Call struct {
	*mock.Call
}

// Verify is a helper method to define mock.On call
//   - secret []byte
//   - value string
func (_e *MockPayloadSigner_Expecter) Verify(secret any, value any) *MockPayloadSigner_Verify_Call {
	return &MockPayloadSigner_Verify_Call{Call: _e.mock.On("Verify", secret, value)}
}

func (_c *MockPayloadSigner_Verify_Call) Run(run func(secret []byte, value string)) *MockPayloadSigner_Verify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPayloadSigner_Verify_Call) Return(data []byte, ok bool) *MockPayloadSigner_Verify_Call {
	_c.Call.Return(data, ok)
	return _c
}

func (_c *MockPayloadSigner_Verify_Call) RunAndReturn(run func(secret []byte, value string) ([]byte, bool)) *MockPayloadSigner_Verify_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOAuthClient creates a new instance of MockOAuthClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOAuthClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOAuthClient {
	mock := &MockOAuthClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOAuthClient is an autogenerated mock type for the OAuthClient type
type MockOAuthClient struct {
	mock.Mock
}

type MockOAuthClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOAuthClient) EXPECT() *MockOAuthClient_Expecter {
	return &MockOAuthClient_Expecter{mock: &_m.Mock}
}

// AuthCodeURL provides a mock function for the type MockOAuthClient
func (_mock *MockOAuthClient) AuthCodeURL(state string, opts ...oauth2.AuthCodeOption) string {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(state, opts)
	} else {
		tmpRet = _mock.Called(state)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for AuthCodeURL")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(string, ...oauth2.AuthCodeOption) string); ok {
		r0 = returnFunc(state, opts...)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockOAuthClient_AuthCodeURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AuthCodeURL'
type MockOAuthClient_AuthCodeURL_Call struct {
	*mock.Call
}

// AuthCodeURL is a helper method to define mock.On call
//   - state string
//   - opts ...oauth2.AuthCodeOption
func (_e *MockOAuthClient_Expecter) AuthCodeURL(state any, opts ...any) *MockOAuthClient_AuthCodeURL_Call {
	return &MockOAuthClient_AuthCodeURL_Call{Call: _e.mock.On("AuthCodeURL",
		append([]any{state}, opts...)...)}
}

func (_c *MockOAuthClient_AuthCodeURL_Call) Run(run func(state string, opts ...oauth2.AuthCodeOption)) *MockOAuthClient_AuthCodeURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []oauth2.AuthCodeOption
		var variadicArgs []oauth2.AuthCodeOption
		if len(args) > 1 {
			variadicArgs = args[1].([]oauth2.AuthCodeOption)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockOAuthClient_AuthCodeURL_Call) Return(s string) *MockOAuthClient_AuthCodeURL_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockOAuthClient_AuthCodeURL_Call) RunAndReturn(run func(state string, opts ...oauth2.AuthCodeOption) string) *MockOAuthClient_AuthCodeURL_Call {
	_c.Call.Return(run)
	return _c
}

// Exchange provides a mock function for the type MockOAuthClient
func (_mock *MockOAuthClient) Exchange(ctx context.Context, code string, opts ...oauth2.AuthCodeOption) (*oauth2.Token, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, code, opts)
	} else {
		tmpRet = _mock.Called(ctx, code)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Exchange")
	}

	var r0 *oauth2.Token
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...oauth2.AuthCodeOption) (*oauth2.Token, error)); ok {
		return returnFunc(ctx, code, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...oauth2.AuthCodeOption) *oauth2.Token); ok {
		r0 = returnFunc(ctx, code, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*oauth2.Token)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...oauth2.AuthCodeOption) error); ok {
		r1 = returnFunc(ctx, code, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOAuthClient_Exchange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exchange'
type MockOAuthClient_Exchange_Call struct {
	*mock.Call
}

// Exchange is a helper method to define mock.On call
//   - ctx context.Context
//   - code string
//   - opts ...oauth2.AuthCodeOption
func (_e *MockOAuthClient_Expecter) Exchange(ctx any, code any, opts ...any) *MockOAuthClient_Exchange_Call {
	return &MockOAuthClient_Exchange_Call{Call: _e.mock.On("Exchange",
		append([]any{ctx, code}, opts...)...)}
}

func (_c *MockOAuthClient_Exchange_Call) Run(run func(ctx context.Context, code string, opts ...oauth2.AuthCodeOption)) *MockOAuthClient_Exchange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []oauth2.AuthCodeOption
		var variadicArgs []oauth2.AuthCodeOption
		if len(args) > 2 {
			variadicArgs = args[2].([]oauth2.AuthCodeOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockOAuthClient_Exchange_Call) Return(token *oauth2.Token, err error) *MockOAuthClient_Exchange_Call {
	_c.Call.Return(token, err)
	return _c
}

func (_c *MockOAuthClient_Exchange_Call) RunAndReturn(run func(ctx context.Context, code string, opts ...oauth2.AuthCodeOption) (*oauth2.Token, error)) *MockOAuthClient_Exchange_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIdToken creates a new instance of MockIdToken. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIdToken(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIdToken {
	mock := &MockIdToken{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIdToken is an autogenerated mock type for the IdToken type
type MockIdToken struct {
	mock.Mock
}

type MockIdToken_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIdToken) EXPECT() *MockIdToken_Expecter {
	return &MockIdToken_Expecter{mock: &_m.Mock}
}

// Claims provides a mock function for the type MockIdToken
func (_mock *MockIdToken) Claims(v any) error {
	ret := _mock.Called(v)

	if len(ret) == 0 {
		panic("no return value specified for Claims")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(any) error); ok {
		r0 = returnFunc(v)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIdToken_Claims_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Claims'
type MockIdToken_Claims_Call struct {
	*mock.Call
}

// Claims is a helper method to define mock.On call
//   - v any
func (_e *MockIdToken_Expecter) Claims(v any) *MockIdToken_Claims_Call {
	return &MockIdToken_Claims_Call{Call: _e.mock.On("Claims", v)}
}

func (_c *MockIdToken_Claims_Call) Run(run func(v any)) *MockIdToken_Claims_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 any
		if args[0] != nil {
			arg0 = args[0].(any)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIdToken_Claims_Call) Return(err error) *MockIdToken_Claims_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIdToken_Claims_Call) RunAndReturn(run func(v any) error) *MockIdToken_Claims_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIdTokenVerifier creates a new instance of MockIdTokenVerifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIdTokenVerifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIdTokenVerifier {
	mock := &MockIdTokenVerifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIdTokenVerifier is an autogenerated mock type for the IdTokenVerifier type
type MockIdTokenVerifier struct {
	mock.Mock
}

type MockIdTokenVerifier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIdTokenVerifier) EXPECT() *MockIdTokenVerifier_Expecter {
	return &MockIdTokenVerifier_Expecter{mock: &_m.Mock}
}

// Verify provides a mock function for the type MockIdTokenVerifier
func (_mock *MockIdTokenVerifier) Verify(ctx context.Context, rawIDToken string) (IdToken, error) {
	ret := _mock.Called(ctx, rawIDToken)

	if len(ret) == 0 {
		panic("no return value specified for Verify")
	}

	var r0 IdToken
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (IdToken, error)); ok {
		return returnFunc(ctx, rawIDToken)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) IdToken); ok {
		r0 = returnFunc(ctx, rawIDToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(IdToken)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, rawIDToken)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIdTokenVerifier_Verify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Verify'
type MockIdTokenVerifier_Verify_Call struct {
	*mock.Call
}

// Verify is a helper method to define mock.On call
//   - ctx context.Context
//   - rawIDToken string
func (_e *MockIdTokenVerifier_Expecter) Verify(ctx any, rawIDToken any) *MockIdTokenVerifier_Verify_Call {
	return &MockIdTokenVerifier_Verify_Call{Call: _e.mock.On("Verify", ctx, rawIDToken)}
}

func (_c *MockIdTokenVerifier_Verify_Call) Run(run func(ctx context.Context, rawIDToken string)) *MockIdTokenVerifier_Verify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIdTokenVerifier_Verify_Call) Return(idToken IdToken, err error) *MockIdTokenVerifier_Verify_Call {
	_c.Call.Return(idToken, err)
	return _c
}

func (_c *MockIdTokenVerifier_Verify_Call) RunAndReturn(run func(ctx context.Context, rawIDToken string) (IdToken, error)) *MockIdTokenVerifier_Verify_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOidcProvider creates a new instance of MockOidcProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOidcProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOidcProvider {
	mock := &MockOidcProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOidcProvider is an autogenerated mock type for the OidcProvider type
type MockOidcProvider struct {
	mock.Mock
}

type MockOidcProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOidcProvider) EXPECT() *MockOidcProvider_Expecter {
	return &MockOidcProvider_Expecter{mock: &_m.Mock}
}

// Endpoint provides a mock function for the type MockOidcProvider
func (_mock *MockOidcProvider) Endpoint() oauth2.Endpoint {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Endpoint")
	}

	var r0 oauth2.Endpoint
	if returnFunc, ok := ret.Get(0).(func() oauth2.Endpoint); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(oauth2.Endpoint)
	}
	return r0
}

// MockOidcProvider_Endpoint_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Endpoint'
type MockOidcProvider_Endpoint_Call struct {
	*mock.Call
}

// Endpoint is a helper method to define mock.On call
func (_e *MockOidcProvider_Expecter) Endpoint() *MockOidcProvider_Endpoint_Call {
	return &MockOidcProvider_Endpoint_Call{Call: _e.mock.On("Endpoint")}
}

func (_c *MockOidcProvider_Endpoint_Call) Run(run func()) *MockOidcProvider_Endpoint_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockOidcProvider_Endpoint_Call) Return(endpoint oauth2.Endpoint) *MockOidcProvider_Endpoint_Call {
	_c.Call.Return(endpoint)
	return _c
}

func (_c *MockOidcProvider_Endpoint_Call) RunAndReturn(run func() oauth2.Endpoint) *MockOidcProvider_Endpoint_Call {
	_c.Call.Return(run)
	return _c
}

// Verifier provides a mock function for the type MockOidcProvider
func (_mock *MockOidcProvider) Verifier(config *oidc.Config) IdTokenVerifier {
	ret := _mock.Called(config)

	if len(ret) == 0 {
		panic("no return value specified for Verifier")
	}

	var r0 IdTokenVerifier
	if returnFunc, ok := ret.Get(0).(func(*oidc.Config) IdTokenVerifier); ok {
		r0 = returnFunc(config)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(IdTokenVerifier)
		}
	}
	return r0
}

// MockOidcProvider_Verifier_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Verifier'
type MockOidcProvider_Verifier_Call struct {
	*mock.Call
}

// Verifier is a helper method to define mock.On call
//   - config *oidc.Config
func (_e *MockOidcProvider_Expecter) Verifier(config any) *MockOidcProvider_Verifier_Call {
	return &MockOidcProvider_Verifier_Call{Call: _e.mock.On("Verifier", config)}
}

func (_c *MockOidcProvider_Verifier_Call) Run(run func(config *oidc.Config)) *MockOidcProvider_Verifier_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *oidc.Config
		if args[0] != nil {
			arg0 = args[0].(*oidc.Config)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockOidcProvider_Verifier_Call) Return(idTokenVerifier IdTokenVerifier) *MockOidcProvider_Verifier_Call {
	_c.Call.Return(idTokenVerifier)
	return _c
}

func (_c *MockOidcProvider_Verifier_Call) RunAndReturn(run func(config *oidc.Config) IdTokenVerifier) *MockOidcProvider_Verifier_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockJsonSerialiser creates a new instance of MockJsonSerialiser. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockJsonSerialiser(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockJsonSerialiser {
	mock := &MockJsonSerialiser{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockJsonSerialiser is an autogenerated mock type for the JsonSerialiser type
type MockJsonSerialiser struct {
	mock.Mock
}

type MockJsonSerialiser_Expecter struct {
	mock *mock.Mock
}

func (_m *MockJsonSerialiser) EXPECT() *MockJsonSerialiser_Expecter {
	return &MockJsonSerialiser_Expecter{mock: &_m.Mock}
}

// Marshal provides a mock function for the type MockJsonSerialiser
func (_mock *MockJsonSerialiser) Marshal(v any) ([]byte, error) {
	ret := _mock.Called(v)

	if len(ret) == 0 {
		panic("no return value specified for Marshal")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(any) ([]byte, error)); ok {
		return returnFunc(v)
	}
	if returnFunc, ok := ret.Get(0).(func(any) []byte); ok {
		r0 = returnFunc(v)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(any) error); ok {
		r1 = returnFunc(v)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockJsonSerialiser_Marshal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Marshal'
type MockJsonSerialiser_Marshal_Call struct {
	*mock.Call
}

// Marshal is a helper method to define mock.On call
//   - v any
func (_e *MockJsonSerialiser_Expecter) Marshal(v any) *MockJsonSerialiser_Marshal_Call {
	return &MockJsonSerialiser_Marshal_Call{Call: _e.mock.On("Marshal", v)}
}

func (_c *MockJsonSerialiser_Marshal_Call) Run(run func(v any)) *MockJsonSerialiser_Marshal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 any
		if args[0] != nil {
			arg0 = args[0].(any)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockJsonSerialiser_Marshal_Call) Return(bytes []byte, err error) *MockJsonSerialiser_Marshal_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockJsonSerialiser_Marshal_Call) RunAndReturn(run func(v any) ([]byte, error)) *MockJsonSerialiser_Marshal_Call {
	_c.Call.Return(run)
	return _c
}

// Unmarshal provides a mock function for the type MockJsonSerialiser
func (_mock *MockJsonSerialiser) Unmarshal(data []byte, v any) error {
	ret := _mock.Called(data, v)

	if len(ret) == 0 {
		panic("no return value specified for Unmarshal")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func([]byte, any) error); ok {
		r0 = returnFunc(data, v)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockJsonSerialiser_Unmarshal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unmarshal'
type MockJsonSerialiser_Unmarshal_Call struct {
	*mock.Call
}

// Unmarshal is a helper method to define mock.On call
//   - data []byte
//   - v any
func (_e *MockJsonSerialiser_Expecter) Unmarshal(data any, v any) *MockJsonSerialiser_Unmarshal_Call {
	return &MockJsonSerialiser_Unmarshal_Call{Call: _e.mock.On("Unmarshal", data, v)}
}

func (_c *MockJsonSerialiser_Unmarshal_Call) Run(run func(data []byte, v any)) *MockJsonSerialiser_Unmarshal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		var arg1 any
		if args[1] != nil {
			arg1 = args[1].(any)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockJsonSerialiser_Unmarshal_Call) Return(err error) *MockJsonSerialiser_Unmarshal_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockJsonSerialiser_Unmarshal_Call) RunAndReturn(run func(data []byte, v any) error) *MockJsonSerialiser_Unmarshal_Call {
	_c.Call.Return(run)
	return _c
}
