// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package services

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/turnerbenjamin/querystack/querymodel"
)

// NewMockAccessPolicy creates a new instance of MockAccessPolicy. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAccessPolicy(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAccessPolicy {
	mock := &MockAccessPolicy{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAccessPolicy is an autogenerated mock type for the AccessPolicy type
type MockAccessPolicy struct {
	mock.Mock
}

type MockAccessPolicy_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAccessPolicy) EXPECT() *MockAccessPolicy_Expecter {
	return &MockAccessPolicy_Expecter{mock: &_m.Mock}
}

// GetTableAccessPolicy provides a mock function for the type MockAccessPolicy
func (_mock *MockAccessPolicy) GetTableAccessPolicy(tableName string) (querymodel.TableAccessPolicy, bool) {
	ret := _mock.Called(tableName)

	if len(ret) == 0 {
		panic("no return value specified for GetTableAccessPolicy")
	}

	var r0 querymodel.TableAccessPolicy
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(string) (querymodel.TableAccessPolicy, bool)); ok {
		return returnFunc(tableName)
	}
	if returnFunc, ok := ret.Get(0).(func(string) querymodel.TableAccessPolicy); ok {
		r0 = returnFunc(tableName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(querymodel.TableAccessPolicy)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) bool); ok {
		r1 = returnFunc(tableName)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// MockAccessPolicy_GetTableAccessPolicy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTableAccessPolicy'
type MockAccessPolicy_GetTableAccessPolicy_Call struct {
	*mock.Call
}

// GetTableAccessPolicy is a helper method to define mock.On call
//   - tableName string
func (_e *MockAccessPolicy_Expecter) GetTableAccessPolicy(tableName any) *MockAccessPolicy_GetTableAccessPolicy_Call {
	return &MockAccessPolicy_GetTableAccessPolicy_Call{Call: _e.mock.On("GetTableAccessPolicy", tableName)}
}

func (_c *MockAccessPolicy_GetTableAccessPolicy_Call) Run(run func(tableName string)) *MockAccessPolicy_GetTableAccessPolicy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAccessPolicy_GetTableAccessPolicy_Call) Return(tableAccessPolicy querymodel.TableAccessPolicy, b bool) *MockAccessPolicy_GetTableAccessPolicy_Call {
	_c.Call.Return(tableAccessPolicy, b)
	return _c
}

func (_c *MockAccessPolicy_GetTableAccessPolicy_Call) RunAndReturn(run func(tableName string) (querymodel.TableAccessPolicy, bool)) *MockAccessPolicy_GetTableAccessPolicy_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// ExecuteJsonRequest provides a mock function for the type MockRepository
func (_mock *MockRepository) ExecuteJsonRequest(ctx context.Context, query querymodel.QueryStatement) ([]byte, error) {
	ret := _mock.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for ExecuteJsonRequest")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, querymodel.QueryStatement) ([]byte, error)); ok {
		return returnFunc(ctx, query)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, querymodel.QueryStatement) []byte); ok {
		r0 = returnFunc(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, querymodel.QueryStatement) error); ok {
		r1 = returnFunc(ctx, query)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_ExecuteJsonRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecuteJsonRequest'
type MockRepository_ExecuteJsonRequest_Call struct {
	*mock.Call
}

// ExecuteJsonRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - query querymodel.QueryStatement
func (_e *MockRepository_Expecter) ExecuteJsonRequest(ctx any, query any) *MockRepository_ExecuteJsonRequest_Call {
	return &MockRepository_ExecuteJsonRequest_Call{Call: _e.mock.On("ExecuteJsonRequest", ctx, query)}
}

func (_c *MockRepository_ExecuteJsonRequest_Call) Run(run func(ctx context.Context, query querymodel.QueryStatement)) *MockRepository_ExecuteJsonRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 querymodel.QueryStatement
		if args[1] != nil {
			arg1 = args[1].(querymodel.QueryStatement)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_ExecuteJsonRequest_Call) Return(bytes []byte, err error) *MockRepository_ExecuteJsonRequest_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockRepository_ExecuteJsonRequest_Call) RunAndReturn(run func(ctx context.Context, query querymodel.QueryStatement) ([]byte, error)) *MockRepository_ExecuteJsonRequest_Call {
	_c.Call.Return(run)
	return _c
}

// ExecuteJsonRequestWithCount provides a mock function for the type MockRepository
func (_mock *MockRepository) ExecuteJsonRequestWithCount(ctx context.Context, mainQuery querymodel.QueryStatement, countQuery querymodel.QueryStatement) ([]byte, *uint64, error) {
	ret := _mock.Called(ctx, mainQuery, countQuery)

	if len(ret) == 0 {
		panic("no return value specified for ExecuteJsonRequestWithCount")
	}

	var r0 []byte
	var r1 *uint64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, querymodel.QueryStatement, querymodel.QueryStatement) ([]byte, *uint64, error)); ok {
		return returnFunc(ctx, mainQuery, countQuery)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, querymodel.QueryStatement, querymodel.QueryStatement) []byte); ok {
		r0 = returnFunc(ctx, mainQuery, countQuery)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, querymodel.QueryStatement, querymodel.QueryStatement) *uint64); ok {
		r1 = returnFunc(ctx, mainQuery, countQuery)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*uint64)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, querymodel.QueryStatement, querymodel.QueryStatement) error); ok {
		r2 = returnFunc(ctx, mainQuery, countQuery)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockRepository_ExecuteJsonRequestWithCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecuteJsonRequestWithCount'
type MockRepository_ExecuteJsonRequestWithCount_Call struct {
	*mock.Call
}

// ExecuteJsonRequestWithCount is a helper method to define mock.On call
//   - ctx context.Context
//   - mainQuery querymodel.QueryStatement
//   - countQuery querymodel.QueryStatement
func (_e *MockRepository_Expecter) ExecuteJsonRequestWithCount(ctx any, mainQuery any, countQuery any) *MockRepository_ExecuteJsonRequestWithCount_Call {
	return &MockRepository_ExecuteJsonRequestWithCount_Call{Call: _e.mock.On("ExecuteJsonRequestWithCount", ctx, mainQuery, countQuery)}
}

func (_c *MockRepository_ExecuteJsonRequestWithCount_Call) Run(run func(ctx context.Context, mainQuery querymodel.QueryStatement, countQuery querymodel.QueryStatement)) *MockRepository_ExecuteJsonRequestWithCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 querymodel.QueryStatement
		if args[1] != nil {
			arg1 = args[1].(querymodel.QueryStatement)
		}
		var arg2 querymodel.QueryStatement
		if args[2] != nil {
			arg2 = args[2].(querymodel.QueryStatement)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_ExecuteJsonRequestWithCount_Call) Return(bytes []byte, v *uint64, err error) *MockRepository_ExecuteJsonRequestWithCount_Call {
	_c.Call.Return(bytes, v, err)
	return _c
}

func (_c *MockRepository_ExecuteJsonRequestWithCount_Call) RunAndReturn(run func(ctx context.Context, mainQuery querymodel.QueryStatement, countQuery querymodel.QueryStatement) ([]byte, *uint64, error)) *MockRepository_ExecuteJsonRequestWithCount_Call {
	_c.Call.Return(run)
	return _c
}
