// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package queryPlanner

import (
	mock "github.com/stretchr/testify/mock"
	"github.com/turnerbenjamin/heterogen_portal/internal/query/paginationTokens"
	"github.com/turnerbenjamin/heterogen_portal/internal/query/queryDataStore"
	"github.com/turnerbenjamin/heterogen_portal/internal/query/queryModel"
)

// NewMockPagingTokenBuilder creates a new instance of MockPagingTokenBuilder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPagingTokenBuilder(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPagingTokenBuilder {
	mock := &MockPagingTokenBuilder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPagingTokenBuilder is an autogenerated mock type for the PagingTokenBuilder type
type MockPagingTokenBuilder struct {
	mock.Mock
}

type MockPagingTokenBuilder_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPagingTokenBuilder) EXPECT() *MockPagingTokenBuilder_Expecter {
	return &MockPagingTokenBuilder_Expecter{mock: &_m.Mock}
}

// BuildToken provides a mock function for the type MockPagingTokenBuilder
func (_mock *MockPagingTokenBuilder) BuildToken(queryDataStore1 queryDataStore.QueryDataStore, lastRecord queryModel.TableModel) (string, error) {
	ret := _mock.Called(queryDataStore1, lastRecord)

	if len(ret) == 0 {
		panic("no return value specified for BuildToken")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(queryDataStore.QueryDataStore, queryModel.TableModel) (string, error)); ok {
		return returnFunc(queryDataStore1, lastRecord)
	}
	if returnFunc, ok := ret.Get(0).(func(queryDataStore.QueryDataStore, queryModel.TableModel) string); ok {
		r0 = returnFunc(queryDataStore1, lastRecord)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(queryDataStore.QueryDataStore, queryModel.TableModel) error); ok {
		r1 = returnFunc(queryDataStore1, lastRecord)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPagingTokenBuilder_BuildToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BuildToken'
type MockPagingTokenBuilder_BuildToken_Call struct {
	*mock.Call
}

// BuildToken is a helper method to define mock.On call
//   - queryDataStore1 queryDataStore.QueryDataStore
//   - lastRecord queryModel.TableModel
func (_e *MockPagingTokenBuilder_Expecter) BuildToken(queryDataStore1 any, lastRecord any) *MockPagingTokenBuilder_BuildToken_Call {
	return &MockPagingTokenBuilder_BuildToken_Call{Call: _e.mock.On("BuildToken", queryDataStore1, lastRecord)}
}

func (_c *MockPagingTokenBuilder_BuildToken_Call) Run(run func(queryDataStore1 queryDataStore.QueryDataStore, lastRecord queryModel.TableModel)) *MockPagingTokenBuilder_BuildToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 queryDataStore.QueryDataStore
		if args[0] != nil {
			arg0 = args[0].(queryDataStore.QueryDataStore)
		}
		var arg1 queryModel.TableModel
		if args[1] != nil {
			arg1 = args[1].(queryModel.TableModel)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPagingTokenBuilder_BuildToken_Call) Return(s string, err error) *MockPagingTokenBuilder_BuildToken_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockPagingTokenBuilder_BuildToken_Call) RunAndReturn(run func(queryDataStore1 queryDataStore.QueryDataStore, lastRecord queryModel.TableModel) (string, error)) *MockPagingTokenBuilder_BuildToken_Call {
	_c.Call.Return(run)
	return _c
}

// ParseToken provides a mock function for the type MockPagingTokenBuilder
func (_mock *MockPagingTokenBuilder) ParseToken(token string, valueBuilder queryModel.ValueBuilder) (*paginationTokens.PagingToken, error) {
	ret := _mock.Called(token, valueBuilder)

	if len(ret) == 0 {
		panic("no return value specified for ParseToken")
	}

	var r0 *paginationTokens.PagingToken
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, queryModel.ValueBuilder) (*paginationTokens.PagingToken, error)); ok {
		return returnFunc(token, valueBuilder)
	}
	if returnFunc, ok := ret.Get(0).(func(string, queryModel.ValueBuilder) *paginationTokens.PagingToken); ok {
		r0 = returnFunc(token, valueBuilder)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*paginationTokens.PagingToken)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, queryModel.ValueBuilder) error); ok {
		r1 = returnFunc(token, valueBuilder)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPagingTokenBuilder_ParseToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ParseToken'
type MockPagingTokenBuilder_ParseToken_Call struct {
	*mock.Call
}

// ParseToken is a helper method to define mock.On call
//   - token string
//   - valueBuilder queryModel.ValueBuilder
func (_e *MockPagingTokenBuilder_Expecter) ParseToken(token any, valueBuilder any) *MockPagingTokenBuilder_ParseToken_Call {
	return &MockPagingTokenBuilder_ParseToken_Call{Call: _e.mock.On("ParseToken", token, valueBuilder)}
}

func (_c *MockPagingTokenBuilder_ParseToken_Call) Run(run func(token string, valueBuilder queryModel.ValueBuilder)) *MockPagingTokenBuilder_ParseToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 queryModel.ValueBuilder
		if args[1] != nil {
			arg1 = args[1].(queryModel.ValueBuilder)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPagingTokenBuilder_ParseToken_Call) Return(pagingToken *paginationTokens.PagingToken, err error) *MockPagingTokenBuilder_ParseToken_Call {
	_c.Call.Return(pagingToken, err)
	return _c
}

func (_c *MockPagingTokenBuilder_ParseToken_Call) RunAndReturn(run func(token string, valueBuilder queryModel.ValueBuilder) (*paginationTokens.PagingToken, error)) *MockPagingTokenBuilder_ParseToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockQueryParser creates a new instance of MockQueryParser. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQueryParser(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQueryParser {
	mock := &MockQueryParser{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockQueryParser is an autogenerated mock type for the QueryParser type
type MockQueryParser struct {
	mock.Mock
}

type MockQueryParser_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQueryParser) EXPECT() *MockQueryParser_Expecter {
	return &MockQueryParser_Expecter{mock: &_m.Mock}
}

// Parse provides a mock function for the type MockQueryParser
func (_mock *MockQueryParser) Parse(queryString string, queryDataStore1 queryDataStore.QueryDataStore) error {
	ret := _mock.Called(queryString, queryDataStore1)

	if len(ret) == 0 {
		panic("no return value specified for Parse")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, queryDataStore.QueryDataStore) error); ok {
		r0 = returnFunc(queryString, queryDataStore1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockQueryParser_Parse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Parse'
type MockQueryParser_Parse_Call struct {
	*mock.Call
}

// Parse is a helper method to define mock.On call
//   - queryString string
//   - queryDataStore1 queryDataStore.QueryDataStore
func (_e *MockQueryParser_Expecter) Parse(queryString any, queryDataStore1 any) *MockQueryParser_Parse_Call {
	return &MockQueryParser_Parse_Call{Call: _e.mock.On("Parse", queryString, queryDataStore1)}
}

func (_c *MockQueryParser_Parse_Call) Run(run func(queryString string, queryDataStore1 queryDataStore.QueryDataStore)) *MockQueryParser_Parse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 queryDataStore.QueryDataStore
		if args[1] != nil {
			arg1 = args[1].(queryDataStore.QueryDataStore)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQueryParser_Parse_Call) Return(err error) *MockQueryParser_Parse_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockQueryParser_Parse_Call) RunAndReturn(run func(queryString string, queryDataStore1 queryDataStore.QueryDataStore) error) *MockQueryParser_Parse_Call {
	_c.Call.Return(run)
	return _c
}
