// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package queryDataStore

import (
	"iter"

	mock "github.com/stretchr/testify/mock"
	"github.com/turnerbenjamin/heterogen_portal/internal/query/queryModel"
	"github.com/turnerbenjamin/heterogen_portal/internal/query/relationships"
)

// NewMockFilterExpressionBuilder creates a new instance of MockFilterExpressionBuilder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFilterExpressionBuilder(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFilterExpressionBuilder {
	mock := &MockFilterExpressionBuilder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFilterExpressionBuilder is an autogenerated mock type for the FilterExpressionBuilder type
type MockFilterExpressionBuilder struct {
	mock.Mock
}

type MockFilterExpressionBuilder_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFilterExpressionBuilder) EXPECT() *MockFilterExpressionBuilder_Expecter {
	return &MockFilterExpressionBuilder_Expecter{mock: &_m.Mock}
}

// NewCollectionExpression provides a mock function for the type MockFilterExpressionBuilder
func (_mock *MockFilterExpressionBuilder) NewCollectionExpression(resourcePath string, operator queryModel.CollectionOperator, filterExpression queryModel.FilterExpression) (*queryModel.CollectionExpression, error) {
	ret := _mock.Called(resourcePath, operator, filterExpression)

	if len(ret) == 0 {
		panic("no return value specified for NewCollectionExpression")
	}

	var r0 *queryModel.CollectionExpression
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, queryModel.CollectionOperator, queryModel.FilterExpression) (*queryModel.CollectionExpression, error)); ok {
		return returnFunc(resourcePath, operator, filterExpression)
	}
	if returnFunc, ok := ret.Get(0).(func(string, queryModel.CollectionOperator, queryModel.FilterExpression) *queryModel.CollectionExpression); ok {
		r0 = returnFunc(resourcePath, operator, filterExpression)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*queryModel.CollectionExpression)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, queryModel.CollectionOperator, queryModel.FilterExpression) error); ok {
		r1 = returnFunc(resourcePath, operator, filterExpression)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFilterExpressionBuilder_NewCollectionExpression_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewCollectionExpression'
type MockFilterExpressionBuilder_NewCollectionExpression_Call struct {
	*mock.Call
}

// NewCollectionExpression is a helper method to define mock.On call
//   - resourcePath string
//   - operator queryModel.CollectionOperator
//   - filterExpression queryModel.FilterExpression
func (_e *MockFilterExpressionBuilder_Expecter) NewCollectionExpression(resourcePath any, operator any, filterExpression any) *MockFilterExpressionBuilder_NewCollectionExpression_Call {
	return &MockFilterExpressionBuilder_NewCollectionExpression_Call{Call: _e.mock.On("NewCollectionExpression", resourcePath, operator, filterExpression)}
}

func (_c *MockFilterExpressionBuilder_NewCollectionExpression_Call) Run(run func(resourcePath string, operator queryModel.CollectionOperator, filterExpression queryModel.FilterExpression)) *MockFilterExpressionBuilder_NewCollectionExpression_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 queryModel.CollectionOperator
		if args[1] != nil {
			arg1 = args[1].(queryModel.CollectionOperator)
		}
		var arg2 queryModel.FilterExpression
		if args[2] != nil {
			arg2 = args[2].(queryModel.FilterExpression)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockFilterExpressionBuilder_NewCollectionExpression_Call) Return(collectionExpression *queryModel.CollectionExpression, err error) *MockFilterExpressionBuilder_NewCollectionExpression_Call {
	_c.Call.Return(collectionExpression, err)
	return _c
}

func (_c *MockFilterExpressionBuilder_NewCollectionExpression_Call) RunAndReturn(run func(resourcePath string, operator queryModel.CollectionOperator, filterExpression queryModel.FilterExpression) (*queryModel.CollectionExpression, error)) *MockFilterExpressionBuilder_NewCollectionExpression_Call {
	_c.Call.Return(run)
	return _c
}

// NewComparisonExpression provides a mock function for the type MockFilterExpressionBuilder
func (_mock *MockFilterExpressionBuilder) NewComparisonExpression(columnPath string, operator queryModel.ComparisonOperator, value queryModel.Value) (*queryModel.ComparisonExpression, error) {
	ret := _mock.Called(columnPath, operator, value)

	if len(ret) == 0 {
		panic("no return value specified for NewComparisonExpression")
	}

	var r0 *queryModel.ComparisonExpression
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, queryModel.ComparisonOperator, queryModel.Value) (*queryModel.ComparisonExpression, error)); ok {
		return returnFunc(columnPath, operator, value)
	}
	if returnFunc, ok := ret.Get(0).(func(string, queryModel.ComparisonOperator, queryModel.Value) *queryModel.ComparisonExpression); ok {
		r0 = returnFunc(columnPath, operator, value)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*queryModel.ComparisonExpression)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, queryModel.ComparisonOperator, queryModel.Value) error); ok {
		r1 = returnFunc(columnPath, operator, value)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFilterExpressionBuilder_NewComparisonExpression_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewComparisonExpression'
type MockFilterExpressionBuilder_NewComparisonExpression_Call struct {
	*mock.Call
}

// NewComparisonExpression is a helper method to define mock.On call
//   - columnPath string
//   - operator queryModel.ComparisonOperator
//   - value queryModel.Value
func (_e *MockFilterExpressionBuilder_Expecter) NewComparisonExpression(columnPath any, operator any, value any) *MockFilterExpressionBuilder_NewComparisonExpression_Call {
	return &MockFilterExpressionBuilder_NewComparisonExpression_Call{Call: _e.mock.On("NewComparisonExpression", columnPath, operator, value)}
}

func (_c *MockFilterExpressionBuilder_NewComparisonExpression_Call) Run(run func(columnPath string, operator queryModel.ComparisonOperator, value queryModel.Value)) *MockFilterExpressionBuilder_NewComparisonExpression_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 queryModel.ComparisonOperator
		if args[1] != nil {
			arg1 = args[1].(queryModel.ComparisonOperator)
		}
		var arg2 queryModel.Value
		if args[2] != nil {
			arg2 = args[2].(queryModel.Value)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockFilterExpressionBuilder_NewComparisonExpression_Call) Return(comparisonExpression *queryModel.ComparisonExpression, err error) *MockFilterExpressionBuilder_NewComparisonExpression_Call {
	_c.Call.Return(comparisonExpression, err)
	return _c
}

func (_c *MockFilterExpressionBuilder_NewComparisonExpression_Call) RunAndReturn(run func(columnPath string, operator queryModel.ComparisonOperator, value queryModel.Value) (*queryModel.ComparisonExpression, error)) *MockFilterExpressionBuilder_NewComparisonExpression_Call {
	_c.Call.Return(run)
	return _c
}

// NewComparisonExpressionFromResolvedColumn provides a mock function for the type MockFilterExpressionBuilder
func (_mock *MockFilterExpressionBuilder) NewComparisonExpressionFromResolvedColumn(column queryModel.ResolvedColumn, operator queryModel.ComparisonOperator, value queryModel.Value) (*queryModel.ComparisonExpression, error) {
	ret := _mock.Called(column, operator, value)

	if len(ret) == 0 {
		panic("no return value specified for NewComparisonExpressionFromResolvedColumn")
	}

	var r0 *queryModel.ComparisonExpression
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(queryModel.ResolvedColumn, queryModel.ComparisonOperator, queryModel.Value) (*queryModel.ComparisonExpression, error)); ok {
		return returnFunc(column, operator, value)
	}
	if returnFunc, ok := ret.Get(0).(func(queryModel.ResolvedColumn, queryModel.ComparisonOperator, queryModel.Value) *queryModel.ComparisonExpression); ok {
		r0 = returnFunc(column, operator, value)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*queryModel.ComparisonExpression)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(queryModel.ResolvedColumn, queryModel.ComparisonOperator, queryModel.Value) error); ok {
		r1 = returnFunc(column, operator, value)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFilterExpressionBuilder_NewComparisonExpressionFromResolvedColumn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewComparisonExpressionFromResolvedColumn'
type MockFilterExpressionBuilder_NewComparisonExpressionFromResolvedColumn_Call struct {
	*mock.Call
}

// NewComparisonExpressionFromResolvedColumn is a helper method to define mock.On call
//   - column queryModel.ResolvedColumn
//   - operator queryModel.ComparisonOperator
//   - value queryModel.Value
func (_e *MockFilterExpressionBuilder_Expecter) NewComparisonExpressionFromResolvedColumn(column any, operator any, value any) *MockFilterExpressionBuilder_NewComparisonExpressionFromResolvedColumn_Call {
	return &MockFilterExpressionBuilder_NewComparisonExpressionFromResolvedColumn_Call{Call: _e.mock.On("NewComparisonExpressionFromResolvedColumn", column, operator, value)}
}

func (_c *MockFilterExpressionBuilder_NewComparisonExpressionFromResolvedColumn_Call) Run(run func(column queryModel.ResolvedColumn, operator queryModel.ComparisonOperator, value queryModel.Value)) *MockFilterExpressionBuilder_NewComparisonExpressionFromResolvedColumn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 queryModel.ResolvedColumn
		if args[0] != nil {
			arg0 = args[0].(queryModel.ResolvedColumn)
		}
		var arg1 queryModel.ComparisonOperator
		if args[1] != nil {
			arg1 = args[1].(queryModel.ComparisonOperator)
		}
		var arg2 queryModel.Value
		if args[2] != nil {
			arg2 = args[2].(queryModel.Value)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockFilterExpressionBuilder_NewComparisonExpressionFromResolvedColumn_Call) Return(comparisonExpression *queryModel.ComparisonExpression, err error) *MockFilterExpressionBuilder_NewComparisonExpressionFromResolvedColumn_Call {
	_c.Call.Return(comparisonExpression, err)
	return _c
}

func (_c *MockFilterExpressionBuilder_NewComparisonExpressionFromResolvedColumn_Call) RunAndReturn(run func(column queryModel.ResolvedColumn, operator queryModel.ComparisonOperator, value queryModel.Value) (*queryModel.ComparisonExpression, error)) *MockFilterExpressionBuilder_NewComparisonExpressionFromResolvedColumn_Call {
	_c.Call.Return(run)
	return _c
}

// NewLogicalExpression provides a mock function for the type MockFilterExpressionBuilder
func (_mock *MockFilterExpressionBuilder) NewLogicalExpression(left queryModel.FilterExpression, operator queryModel.LogicalOperator, right queryModel.FilterExpression) (*queryModel.LogicalExpression, error) {
	ret := _mock.Called(left, operator, right)

	if len(ret) == 0 {
		panic("no return value specified for NewLogicalExpression")
	}

	var r0 *queryModel.LogicalExpression
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(queryModel.FilterExpression, queryModel.LogicalOperator, queryModel.FilterExpression) (*queryModel.LogicalExpression, error)); ok {
		return returnFunc(left, operator, right)
	}
	if returnFunc, ok := ret.Get(0).(func(queryModel.FilterExpression, queryModel.LogicalOperator, queryModel.FilterExpression) *queryModel.LogicalExpression); ok {
		r0 = returnFunc(left, operator, right)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*queryModel.LogicalExpression)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(queryModel.FilterExpression, queryModel.LogicalOperator, queryModel.FilterExpression) error); ok {
		r1 = returnFunc(left, operator, right)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFilterExpressionBuilder_NewLogicalExpression_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewLogicalExpression'
type MockFilterExpressionBuilder_NewLogicalExpression_Call struct {
	*mock.Call
}

// NewLogicalExpression is a helper method to define mock.On call
//   - left queryModel.FilterExpression
//   - operator queryModel.LogicalOperator
//   - right queryModel.FilterExpression
func (_e *MockFilterExpressionBuilder_Expecter) NewLogicalExpression(left any, operator any, right any) *MockFilterExpressionBuilder_NewLogicalExpression_Call {
	return &MockFilterExpressionBuilder_NewLogicalExpression_Call{Call: _e.mock.On("NewLogicalExpression", left, operator, right)}
}

func (_c *MockFilterExpressionBuilder_NewLogicalExpression_Call) Run(run func(left queryModel.FilterExpression, operator queryModel.LogicalOperator, right queryModel.FilterExpression)) *MockFilterExpressionBuilder_NewLogicalExpression_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 queryModel.FilterExpression
		if args[0] != nil {
			arg0 = args[0].(queryModel.FilterExpression)
		}
		var arg1 queryModel.LogicalOperator
		if args[1] != nil {
			arg1 = args[1].(queryModel.LogicalOperator)
		}
		var arg2 queryModel.FilterExpression
		if args[2] != nil {
			arg2 = args[2].(queryModel.FilterExpression)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockFilterExpressionBuilder_NewLogicalExpression_Call) Return(logicalExpression *queryModel.LogicalExpression, err error) *MockFilterExpressionBuilder_NewLogicalExpression_Call {
	_c.Call.Return(logicalExpression, err)
	return _c
}

func (_c *MockFilterExpressionBuilder_NewLogicalExpression_Call) RunAndReturn(run func(left queryModel.FilterExpression, operator queryModel.LogicalOperator, right queryModel.FilterExpression) (*queryModel.LogicalExpression, error)) *MockFilterExpressionBuilder_NewLogicalExpression_Call {
	_c.Call.Return(run)
	return _c
}

// ValueBuilder provides a mock function for the type MockFilterExpressionBuilder
func (_mock *MockFilterExpressionBuilder) ValueBuilder() queryModel.ValueBuilder {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ValueBuilder")
	}

	var r0 queryModel.ValueBuilder
	if returnFunc, ok := ret.Get(0).(func() queryModel.ValueBuilder); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(queryModel.ValueBuilder)
		}
	}
	return r0
}

// MockFilterExpressionBuilder_ValueBuilder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValueBuilder'
type MockFilterExpressionBuilder_ValueBuilder_Call struct {
	*mock.Call
}

// ValueBuilder is a helper method to define mock.On call
func (_e *MockFilterExpressionBuilder_Expecter) ValueBuilder() *MockFilterExpressionBuilder_ValueBuilder_Call {
	return &MockFilterExpressionBuilder_ValueBuilder_Call{Call: _e.mock.On("ValueBuilder")}
}

func (_c *MockFilterExpressionBuilder_ValueBuilder_Call) Run(run func()) *MockFilterExpressionBuilder_ValueBuilder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFilterExpressionBuilder_ValueBuilder_Call) Return(valueBuilder queryModel.ValueBuilder) *MockFilterExpressionBuilder_ValueBuilder_Call {
	_c.Call.Return(valueBuilder)
	return _c
}

func (_c *MockFilterExpressionBuilder_ValueBuilder_Call) RunAndReturn(run func() queryModel.ValueBuilder) *MockFilterExpressionBuilder_ValueBuilder_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockQueryDataStore creates a new instance of MockQueryDataStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQueryDataStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQueryDataStore {
	mock := &MockQueryDataStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockQueryDataStore is an autogenerated mock type for the QueryDataStore type
type MockQueryDataStore struct {
	mock.Mock
}

type MockQueryDataStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQueryDataStore) EXPECT() *MockQueryDataStore_Expecter {
	return &MockQueryDataStore_Expecter{mock: &_m.Mock}
}

// AddAssociatedWithParentFilter provides a mock function for the type MockQueryDataStore
func (_mock *MockQueryDataStore) AddAssociatedWithParentFilter(linkFromParent queryModel.TraversalStep, joinParentOnValues []queryModel.Value) error {
	ret := _mock.Called(linkFromParent, joinParentOnValues)

	if len(ret) == 0 {
		panic("no return value specified for AddAssociatedWithParentFilter")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(queryModel.TraversalStep, []queryModel.Value) error); ok {
		r0 = returnFunc(linkFromParent, joinParentOnValues)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockQueryDataStore_AddAssociatedWithParentFilter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddAssociatedWithParentFilter'
type MockQueryDataStore_AddAssociatedWithParentFilter_Call struct {
	*mock.Call
}

// AddAssociatedWithParentFilter is a helper method to define mock.On call
//   - linkFromParent queryModel.TraversalStep
//   - joinParentOnValues []queryModel.Value
func (_e *MockQueryDataStore_Expecter) AddAssociatedWithParentFilter(linkFromParent any, joinParentOnValues any) *MockQueryDataStore_AddAssociatedWithParentFilter_Call {
	return &MockQueryDataStore_AddAssociatedWithParentFilter_Call{Call: _e.mock.On("AddAssociatedWithParentFilter", linkFromParent, joinParentOnValues)}
}

func (_c *MockQueryDataStore_AddAssociatedWithParentFilter_Call) Run(run func(linkFromParent queryModel.TraversalStep, joinParentOnValues []queryModel.Value)) *MockQueryDataStore_AddAssociatedWithParentFilter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 queryModel.TraversalStep
		if args[0] != nil {
			arg0 = args[0].(queryModel.TraversalStep)
		}
		var arg1 []queryModel.Value
		if args[1] != nil {
			arg1 = args[1].([]queryModel.Value)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQueryDataStore_AddAssociatedWithParentFilter_Call) Return(err error) *MockQueryDataStore_AddAssociatedWithParentFilter_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockQueryDataStore_AddAssociatedWithParentFilter_Call) RunAndReturn(run func(linkFromParent queryModel.TraversalStep, joinParentOnValues []queryModel.Value) error) *MockQueryDataStore_AddAssociatedWithParentFilter_Call {
	_c.Call.Return(run)
	return _c
}

// AddExpand provides a mock function for the type MockQueryDataStore
func (_mock *MockQueryDataStore) AddExpand(relationshipId string) (QueryDataStore, error) {
	ret := _mock.Called(relationshipId)

	if len(ret) == 0 {
		panic("no return value specified for AddExpand")
	}

	var r0 QueryDataStore
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (QueryDataStore, error)); ok {
		return returnFunc(relationshipId)
	}
	if returnFunc, ok := ret.Get(0).(func(string) QueryDataStore); ok {
		r0 = returnFunc(relationshipId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(QueryDataStore)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(relationshipId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQueryDataStore_AddExpand_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddExpand'
type MockQueryDataStore_AddExpand_Call struct {
	*mock.Call
}

// AddExpand is a helper method to define mock.On call
//   - relationshipId string
func (_e *MockQueryDataStore_Expecter) AddExpand(relationshipId any) *MockQueryDataStore_AddExpand_Call {
	return &MockQueryDataStore_AddExpand_Call{Call: _e.mock.On("AddExpand", relationshipId)}
}

func (_c *MockQueryDataStore_AddExpand_Call) Run(run func(relationshipId string)) *MockQueryDataStore_AddExpand_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockQueryDataStore_AddExpand_Call) Return(queryDataStore QueryDataStore, err error) *MockQueryDataStore_AddExpand_Call {
	_c.Call.Return(queryDataStore, err)
	return _c
}

func (_c *MockQueryDataStore_AddExpand_Call) RunAndReturn(run func(relationshipId string) (QueryDataStore, error)) *MockQueryDataStore_AddExpand_Call {
	_c.Call.Return(run)
	return _c
}

// AddOrderBy provides a mock function for the type MockQueryDataStore
func (_mock *MockQueryDataStore) AddOrderBy(columnPath string, dir queryModel.SortDirectionOperator) error {
	ret := _mock.Called(columnPath, dir)

	if len(ret) == 0 {
		panic("no return value specified for AddOrderBy")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, queryModel.SortDirectionOperator) error); ok {
		r0 = returnFunc(columnPath, dir)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockQueryDataStore_AddOrderBy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddOrderBy'
type MockQueryDataStore_AddOrderBy_Call struct {
	*mock.Call
}

// AddOrderBy is a helper method to define mock.On call
//   - columnPath string
//   - dir queryModel.SortDirectionOperator
func (_e *MockQueryDataStore_Expecter) AddOrderBy(columnPath any, dir any) *MockQueryDataStore_AddOrderBy_Call {
	return &MockQueryDataStore_AddOrderBy_Call{Call: _e.mock.On("AddOrderBy", columnPath, dir)}
}

func (_c *MockQueryDataStore_AddOrderBy_Call) Run(run func(columnPath string, dir queryModel.SortDirectionOperator)) *MockQueryDataStore_AddOrderBy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 queryModel.SortDirectionOperator
		if args[1] != nil {
			arg1 = args[1].(queryModel.SortDirectionOperator)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQueryDataStore_AddOrderBy_Call) Return(err error) *MockQueryDataStore_AddOrderBy_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockQueryDataStore_AddOrderBy_Call) RunAndReturn(run func(columnPath string, dir queryModel.SortDirectionOperator) error) *MockQueryDataStore_AddOrderBy_Call {
	_c.Call.Return(run)
	return _c
}

// AddSelect provides a mock function for the type MockQueryDataStore
func (_mock *MockQueryDataStore) AddSelect(columnName string) error {
	ret := _mock.Called(columnName)

	if len(ret) == 0 {
		panic("no return value specified for AddSelect")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(columnName)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockQueryDataStore_AddSelect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddSelect'
type MockQueryDataStore_AddSelect_Call struct {
	*mock.Call
}

// AddSelect is a helper method to define mock.On call
//   - columnName string
func (_e *MockQueryDataStore_Expecter) AddSelect(columnName any) *MockQueryDataStore_AddSelect_Call {
	return &MockQueryDataStore_AddSelect_Call{Call: _e.mock.On("AddSelect", columnName)}
}

func (_c *MockQueryDataStore_AddSelect_Call) Run(run func(columnName string)) *MockQueryDataStore_AddSelect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockQueryDataStore_AddSelect_Call) Return(err error) *MockQueryDataStore_AddSelect_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockQueryDataStore_AddSelect_Call) RunAndReturn(run func(columnName string) error) *MockQueryDataStore_AddSelect_Call {
	_c.Call.Return(run)
	return _c
}

// AddSystemExpand provides a mock function for the type MockQueryDataStore
func (_mock *MockQueryDataStore) AddSystemExpand(relationshipId string) (QueryDataStore, error) {
	ret := _mock.Called(relationshipId)

	if len(ret) == 0 {
		panic("no return value specified for AddSystemExpand")
	}

	var r0 QueryDataStore
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (QueryDataStore, error)); ok {
		return returnFunc(relationshipId)
	}
	if returnFunc, ok := ret.Get(0).(func(string) QueryDataStore); ok {
		r0 = returnFunc(relationshipId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(QueryDataStore)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(relationshipId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQueryDataStore_AddSystemExpand_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddSystemExpand'
type MockQueryDataStore_AddSystemExpand_Call struct {
	*mock.Call
}

// AddSystemExpand is a helper method to define mock.On call
//   - relationshipId string
func (_e *MockQueryDataStore_Expecter) AddSystemExpand(relationshipId any) *MockQueryDataStore_AddSystemExpand_Call {
	return &MockQueryDataStore_AddSystemExpand_Call{Call: _e.mock.On("AddSystemExpand", relationshipId)}
}

func (_c *MockQueryDataStore_AddSystemExpand_Call) Run(run func(relationshipId string)) *MockQueryDataStore_AddSystemExpand_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockQueryDataStore_AddSystemExpand_Call) Return(queryDataStore QueryDataStore, err error) *MockQueryDataStore_AddSystemExpand_Call {
	_c.Call.Return(queryDataStore, err)
	return _c
}

func (_c *MockQueryDataStore_AddSystemExpand_Call) RunAndReturn(run func(relationshipId string) (QueryDataStore, error)) *MockQueryDataStore_AddSystemExpand_Call {
	_c.Call.Return(run)
	return _c
}

// AddSystemSelect provides a mock function for the type MockQueryDataStore
func (_mock *MockQueryDataStore) AddSystemSelect(columnName string) error {
	ret := _mock.Called(columnName)

	if len(ret) == 0 {
		panic("no return value specified for AddSystemSelect")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(columnName)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockQueryDataStore_AddSystemSelect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddSystemSelect'
type MockQueryDataStore_AddSystemSelect_Call struct {
	*mock.Call
}

// AddSystemSelect is a helper method to define mock.On call
//   - columnName string
func (_e *MockQueryDataStore_Expecter) AddSystemSelect(columnName any) *MockQueryDataStore_AddSystemSelect_Call {
	return &MockQueryDataStore_AddSystemSelect_Call{Call: _e.mock.On("AddSystemSelect", columnName)}
}

func (_c *MockQueryDataStore_AddSystemSelect_Call) Run(run func(columnName string)) *MockQueryDataStore_AddSystemSelect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockQueryDataStore_AddSystemSelect_Call) Return(err error) *MockQueryDataStore_AddSystemSelect_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockQueryDataStore_AddSystemSelect_Call) RunAndReturn(run func(columnName string) error) *MockQueryDataStore_AddSystemSelect_Call {
	_c.Call.Return(run)
	return _c
}

// DoCount provides a mock function for the type MockQueryDataStore
func (_mock *MockQueryDataStore) DoCount() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for DoCount")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockQueryDataStore_DoCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DoCount'
type MockQueryDataStore_DoCount_Call struct {
	*mock.Call
}

// DoCount is a helper method to define mock.On call
func (_e *MockQueryDataStore_Expecter) DoCount() *MockQueryDataStore_DoCount_Call {
	return &MockQueryDataStore_DoCount_Call{Call: _e.mock.On("DoCount")}
}

func (_c *MockQueryDataStore_DoCount_Call) Run(run func()) *MockQueryDataStore_DoCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockQueryDataStore_DoCount_Call) Return(b bool) *MockQueryDataStore_DoCount_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockQueryDataStore_DoCount_Call) RunAndReturn(run func() bool) *MockQueryDataStore_DoCount_Call {
	_c.Call.Return(run)
	return _c
}

// Expands provides a mock function for the type MockQueryDataStore
func (_mock *MockQueryDataStore) Expands() iter.Seq2[string, Expansion] {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Expands")
	}

	var r0 iter.Seq2[string, Expansion]
	if returnFunc, ok := ret.Get(0).(func() iter.Seq2[string, Expansion]); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(iter.Seq2[string, Expansion])
		}
	}
	return r0
}

// MockQueryDataStore_Expands_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Expands'
type MockQueryDataStore_Expands_Call struct {
	*mock.Call
}

// Expands is a helper method to define mock.On call
func (_e *MockQueryDataStore_Expecter) Expands() *MockQueryDataStore_Expands_Call {
	return &MockQueryDataStore_Expands_Call{Call: _e.mock.On("Expands")}
}

func (_c *MockQueryDataStore_Expands_Call) Run(run func()) *MockQueryDataStore_Expands_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockQueryDataStore_Expands_Call) Return(seq2 iter.Seq2[string, Expansion]) *MockQueryDataStore_Expands_Call {
	_c.Call.Return(seq2)
	return _c
}

func (_c *MockQueryDataStore_Expands_Call) RunAndReturn(run func() iter.Seq2[string, Expansion]) *MockQueryDataStore_Expands_Call {
	_c.Call.Return(run)
	return _c
}

// ExpandsLen provides a mock function for the type MockQueryDataStore
func (_mock *MockQueryDataStore) ExpandsLen() int {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ExpandsLen")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func() int); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// MockQueryDataStore_ExpandsLen_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExpandsLen'
type MockQueryDataStore_ExpandsLen_Call struct {
	*mock.Call
}

// ExpandsLen is a helper method to define mock.On call
func (_e *MockQueryDataStore_Expecter) ExpandsLen() *MockQueryDataStore_ExpandsLen_Call {
	return &MockQueryDataStore_ExpandsLen_Call{Call: _e.mock.On("ExpandsLen")}
}

func (_c *MockQueryDataStore_ExpandsLen_Call) Run(run func()) *MockQueryDataStore_ExpandsLen_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockQueryDataStore_ExpandsLen_Call) Return(n int) *MockQueryDataStore_ExpandsLen_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockQueryDataStore_ExpandsLen_Call) RunAndReturn(run func() int) *MockQueryDataStore_ExpandsLen_Call {
	_c.Call.Return(run)
	return _c
}

// FilterExpression provides a mock function for the type MockQueryDataStore
func (_mock *MockQueryDataStore) FilterExpression() queryModel.FilterExpression {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for FilterExpression")
	}

	var r0 queryModel.FilterExpression
	if returnFunc, ok := ret.Get(0).(func() queryModel.FilterExpression); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(queryModel.FilterExpression)
		}
	}
	return r0
}

// MockQueryDataStore_FilterExpression_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FilterExpression'
type MockQueryDataStore_FilterExpression_Call struct {
	*mock.Call
}

// FilterExpression is a helper method to define mock.On call
func (_e *MockQueryDataStore_Expecter) FilterExpression() *MockQueryDataStore_FilterExpression_Call {
	return &MockQueryDataStore_FilterExpression_Call{Call: _e.mock.On("FilterExpression")}
}

func (_c *MockQueryDataStore_FilterExpression_Call) Run(run func()) *MockQueryDataStore_FilterExpression_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockQueryDataStore_FilterExpression_Call) Return(filterExpression queryModel.FilterExpression) *MockQueryDataStore_FilterExpression_Call {
	_c.Call.Return(filterExpression)
	return _c
}

func (_c *MockQueryDataStore_FilterExpression_Call) RunAndReturn(run func() queryModel.FilterExpression) *MockQueryDataStore_FilterExpression_Call {
	_c.Call.Return(run)
	return _c
}

// FilterExpressionBuilder provides a mock function for the type MockQueryDataStore
func (_mock *MockQueryDataStore) FilterExpressionBuilder() FilterExpressionBuilder {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for FilterExpressionBuilder")
	}

	var r0 FilterExpressionBuilder
	if returnFunc, ok := ret.Get(0).(func() FilterExpressionBuilder); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(FilterExpressionBuilder)
		}
	}
	return r0
}

// MockQueryDataStore_FilterExpressionBuilder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FilterExpressionBuilder'
type MockQueryDataStore_FilterExpressionBuilder_Call struct {
	*mock.Call
}

// FilterExpressionBuilder is a helper method to define mock.On call
func (_e *MockQueryDataStore_Expecter) FilterExpressionBuilder() *MockQueryDataStore_FilterExpressionBuilder_Call {
	return &MockQueryDataStore_FilterExpressionBuilder_Call{Call: _e.mock.On("FilterExpressionBuilder")}
}

func (_c *MockQueryDataStore_FilterExpressionBuilder_Call) Run(run func()) *MockQueryDataStore_FilterExpressionBuilder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockQueryDataStore_FilterExpressionBuilder_Call) Return(filterExpressionBuilder FilterExpressionBuilder) *MockQueryDataStore_FilterExpressionBuilder_Call {
	_c.Call.Return(filterExpressionBuilder)
	return _c
}

func (_c *MockQueryDataStore_FilterExpressionBuilder_Call) RunAndReturn(run func() FilterExpressionBuilder) *MockQueryDataStore_FilterExpressionBuilder_Call {
	_c.Call.Return(run)
	return _c
}

// GetAliasStore provides a mock function for the type MockQueryDataStore
func (_mock *MockQueryDataStore) GetAliasStore() relationships.AliasStore {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAliasStore")
	}

	var r0 relationships.AliasStore
	if returnFunc, ok := ret.Get(0).(func() relationships.AliasStore); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(relationships.AliasStore)
	}
	return r0
}

// MockQueryDataStore_GetAliasStore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAliasStore'
type MockQueryDataStore_GetAliasStore_Call struct {
	*mock.Call
}

// GetAliasStore is a helper method to define mock.On call
func (_e *MockQueryDataStore_Expecter) GetAliasStore() *MockQueryDataStore_GetAliasStore_Call {
	return &MockQueryDataStore_GetAliasStore_Call{Call: _e.mock.On("GetAliasStore")}
}

func (_c *MockQueryDataStore_GetAliasStore_Call) Run(run func()) *MockQueryDataStore_GetAliasStore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockQueryDataStore_GetAliasStore_Call) Return(aliasStore relationships.AliasStore) *MockQueryDataStore_GetAliasStore_Call {
	_c.Call.Return(aliasStore)
	return _c
}

func (_c *MockQueryDataStore_GetAliasStore_Call) RunAndReturn(run func() relationships.AliasStore) *MockQueryDataStore_GetAliasStore_Call {
	_c.Call.Return(run)
	return _c
}

// GetExpansionByRelationshipId provides a mock function for the type MockQueryDataStore
func (_mock *MockQueryDataStore) GetExpansionByRelationshipId(relationshipId string) (Expansion, bool) {
	ret := _mock.Called(relationshipId)

	if len(ret) == 0 {
		panic("no return value specified for GetExpansionByRelationshipId")
	}

	var r0 Expansion
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(string) (Expansion, bool)); ok {
		return returnFunc(relationshipId)
	}
	if returnFunc, ok := ret.Get(0).(func(string) Expansion); ok {
		r0 = returnFunc(relationshipId)
	} else {
		r0 = ret.Get(0).(Expansion)
	}
	if returnFunc, ok := ret.Get(1).(func(string) bool); ok {
		r1 = returnFunc(relationshipId)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// MockQueryDataStore_GetExpansionByRelationshipId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetExpansionByRelationshipId'
type MockQueryDataStore_GetExpansionByRelationshipId_Call struct {
	*mock.Call
}

// GetExpansionByRelationshipId is a helper method to define mock.On call
//   - relationshipId string
func (_e *MockQueryDataStore_Expecter) GetExpansionByRelationshipId(relationshipId any) *MockQueryDataStore_GetExpansionByRelationshipId_Call {
	return &MockQueryDataStore_GetExpansionByRelationshipId_Call{Call: _e.mock.On("GetExpansionByRelationshipId", relationshipId)}
}

func (_c *MockQueryDataStore_GetExpansionByRelationshipId_Call) Run(run func(relationshipId string)) *MockQueryDataStore_GetExpansionByRelationshipId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockQueryDataStore_GetExpansionByRelationshipId_Call) Return(expansion Expansion, b bool) *MockQueryDataStore_GetExpansionByRelationshipId_Call {
	_c.Call.Return(expansion, b)
	return _c
}

func (_c *MockQueryDataStore_GetExpansionByRelationshipId_Call) RunAndReturn(run func(relationshipId string) (Expansion, bool)) *MockQueryDataStore_GetExpansionByRelationshipId_Call {
	_c.Call.Return(run)
	return _c
}

// IsTopLevelQuery provides a mock function for the type MockQueryDataStore
func (_mock *MockQueryDataStore) IsTopLevelQuery() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsTopLevelQuery")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockQueryDataStore_IsTopLevelQuery_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsTopLevelQuery'
type MockQueryDataStore_IsTopLevelQuery_Call struct {
	*mock.Call
}

// IsTopLevelQuery is a helper method to define mock.On call
func (_e *MockQueryDataStore_Expecter) IsTopLevelQuery() *MockQueryDataStore_IsTopLevelQuery_Call {
	return &MockQueryDataStore_IsTopLevelQuery_Call{Call: _e.mock.On("IsTopLevelQuery")}
}

func (_c *MockQueryDataStore_IsTopLevelQuery_Call) Run(run func()) *MockQueryDataStore_IsTopLevelQuery_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockQueryDataStore_IsTopLevelQuery_Call) Return(b bool) *MockQueryDataStore_IsTopLevelQuery_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockQueryDataStore_IsTopLevelQuery_Call) RunAndReturn(run func() bool) *MockQueryDataStore_IsTopLevelQuery_Call {
	_c.Call.Return(run)
	return _c
}

// JoinCollection provides a mock function for the type MockQueryDataStore
func (_mock *MockQueryDataStore) JoinCollection() relationships.JoinCollection {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for JoinCollection")
	}

	var r0 relationships.JoinCollection
	if returnFunc, ok := ret.Get(0).(func() relationships.JoinCollection); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(relationships.JoinCollection)
	}
	return r0
}

// MockQueryDataStore_JoinCollection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'JoinCollection'
type MockQueryDataStore_JoinCollection_Call struct {
	*mock.Call
}

// JoinCollection is a helper method to define mock.On call
func (_e *MockQueryDataStore_Expecter) JoinCollection() *MockQueryDataStore_JoinCollection_Call {
	return &MockQueryDataStore_JoinCollection_Call{Call: _e.mock.On("JoinCollection")}
}

func (_c *MockQueryDataStore_JoinCollection_Call) Run(run func()) *MockQueryDataStore_JoinCollection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockQueryDataStore_JoinCollection_Call) Return(joinCollection relationships.JoinCollection) *MockQueryDataStore_JoinCollection_Call {
	_c.Call.Return(joinCollection)
	return _c
}

func (_c *MockQueryDataStore_JoinCollection_Call) RunAndReturn(run func() relationships.JoinCollection) *MockQueryDataStore_JoinCollection_Call {
	_c.Call.Return(run)
	return _c
}

// Limit provides a mock function for the type MockQueryDataStore
func (_mock *MockQueryDataStore) Limit() uint16 {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Limit")
	}

	var r0 uint16
	if returnFunc, ok := ret.Get(0).(func() uint16); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(uint16)
	}
	return r0
}

// MockQueryDataStore_Limit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Limit'
type MockQueryDataStore_Limit_Call struct {
	*mock.Call
}

// Limit is a helper method to define mock.On call
func (_e *MockQueryDataStore_Expecter) Limit() *MockQueryDataStore_Limit_Call {
	return &MockQueryDataStore_Limit_Call{Call: _e.mock.On("Limit")}
}

func (_c *MockQueryDataStore_Limit_Call) Run(run func()) *MockQueryDataStore_Limit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockQueryDataStore_Limit_Call) Return(v uint16) *MockQueryDataStore_Limit_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *MockQueryDataStore_Limit_Call) RunAndReturn(run func() uint16) *MockQueryDataStore_Limit_Call {
	_c.Call.Return(run)
	return _c
}

// OrderBy provides a mock function for the type MockQueryDataStore
func (_mock *MockQueryDataStore) OrderBy() iter.Seq[queryModel.SortingRule] {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for OrderBy")
	}

	var r0 iter.Seq[queryModel.SortingRule]
	if returnFunc, ok := ret.Get(0).(func() iter.Seq[queryModel.SortingRule]); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(iter.Seq[queryModel.SortingRule])
		}
	}
	return r0
}

// MockQueryDataStore_OrderBy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OrderBy'
type MockQueryDataStore_OrderBy_Call struct {
	*mock.Call
}

// OrderBy is a helper method to define mock.On call
func (_e *MockQueryDataStore_Expecter) OrderBy() *MockQueryDataStore_OrderBy_Call {
	return &MockQueryDataStore_OrderBy_Call{Call: _e.mock.On("OrderBy")}
}

func (_c *MockQueryDataStore_OrderBy_Call) Run(run func()) *MockQueryDataStore_OrderBy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockQueryDataStore_OrderBy_Call) Return(seq iter.Seq[queryModel.SortingRule]) *MockQueryDataStore_OrderBy_Call {
	_c.Call.Return(seq)
	return _c
}

func (_c *MockQueryDataStore_OrderBy_Call) RunAndReturn(run func() iter.Seq[queryModel.SortingRule]) *MockQueryDataStore_OrderBy_Call {
	_c.Call.Return(run)
	return _c
}

// OrderByLen provides a mock function for the type MockQueryDataStore
func (_mock *MockQueryDataStore) OrderByLen() int {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for OrderByLen")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func() int); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// MockQueryDataStore_OrderByLen_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OrderByLen'
type MockQueryDataStore_OrderByLen_Call struct {
	*mock.Call
}

// OrderByLen is a helper method to define mock.On call
func (_e *MockQueryDataStore_Expecter) OrderByLen() *MockQueryDataStore_OrderByLen_Call {
	return &MockQueryDataStore_OrderByLen_Call{Call: _e.mock.On("OrderByLen")}
}

func (_c *MockQueryDataStore_OrderByLen_Call) Run(run func()) *MockQueryDataStore_OrderByLen_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockQueryDataStore_OrderByLen_Call) Return(n int) *MockQueryDataStore_OrderByLen_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockQueryDataStore_OrderByLen_Call) RunAndReturn(run func() int) *MockQueryDataStore_OrderByLen_Call {
	_c.Call.Return(run)
	return _c
}

// PagingToken provides a mock function for the type MockQueryDataStore
func (_mock *MockQueryDataStore) PagingToken() (string, bool) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for PagingToken")
	}

	var r0 string
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func() (string, bool)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() bool); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// MockQueryDataStore_PagingToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PagingToken'
type MockQueryDataStore_PagingToken_Call struct {
	*mock.Call
}

// PagingToken is a helper method to define mock.On call
func (_e *MockQueryDataStore_Expecter) PagingToken() *MockQueryDataStore_PagingToken_Call {
	return &MockQueryDataStore_PagingToken_Call{Call: _e.mock.On("PagingToken")}
}

func (_c *MockQueryDataStore_PagingToken_Call) Run(run func()) *MockQueryDataStore_PagingToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockQueryDataStore_PagingToken_Call) Return(s string, b bool) *MockQueryDataStore_PagingToken_Call {
	_c.Call.Return(s, b)
	return _c
}

func (_c *MockQueryDataStore_PagingToken_Call) RunAndReturn(run func() (string, bool)) *MockQueryDataStore_PagingToken_Call {
	_c.Call.Return(run)
	return _c
}

// Projection provides a mock function for the type MockQueryDataStore
func (_mock *MockQueryDataStore) Projection() queryModel.Projection {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Projection")
	}

	var r0 queryModel.Projection
	if returnFunc, ok := ret.Get(0).(func() queryModel.Projection); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(queryModel.Projection)
		}
	}
	return r0
}

// MockQueryDataStore_Projection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Projection'
type MockQueryDataStore_Projection_Call struct {
	*mock.Call
}

// Projection is a helper method to define mock.On call
func (_e *MockQueryDataStore_Expecter) Projection() *MockQueryDataStore_Projection_Call {
	return &MockQueryDataStore_Projection_Call{Call: _e.mock.On("Projection")}
}

func (_c *MockQueryDataStore_Projection_Call) Run(run func()) *MockQueryDataStore_Projection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockQueryDataStore_Projection_Call) Return(projection queryModel.Projection) *MockQueryDataStore_Projection_Call {
	_c.Call.Return(projection)
	return _c
}

func (_c *MockQueryDataStore_Projection_Call) RunAndReturn(run func() queryModel.Projection) *MockQueryDataStore_Projection_Call {
	_c.Call.Return(run)
	return _c
}

// QueryString provides a mock function for the type MockQueryDataStore
func (_mock *MockQueryDataStore) QueryString() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for QueryString")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockQueryDataStore_QueryString_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryString'
type MockQueryDataStore_QueryString_Call struct {
	*mock.Call
}

// QueryString is a helper method to define mock.On call
func (_e *MockQueryDataStore_Expecter) QueryString() *MockQueryDataStore_QueryString_Call {
	return &MockQueryDataStore_QueryString_Call{Call: _e.mock.On("QueryString")}
}

func (_c *MockQueryDataStore_QueryString_Call) Run(run func()) *MockQueryDataStore_QueryString_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockQueryDataStore_QueryString_Call) Return(s string) *MockQueryDataStore_QueryString_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockQueryDataStore_QueryString_Call) RunAndReturn(run func() string) *MockQueryDataStore_QueryString_Call {
	_c.Call.Return(run)
	return _c
}

// RootResource provides a mock function for the type MockQueryDataStore
func (_mock *MockQueryDataStore) RootResource() queryModel.TableMetadata {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for RootResource")
	}

	var r0 queryModel.TableMetadata
	if returnFunc, ok := ret.Get(0).(func() queryModel.TableMetadata); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(queryModel.TableMetadata)
		}
	}
	return r0
}

// MockQueryDataStore_RootResource_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RootResource'
type MockQueryDataStore_RootResource_Call struct {
	*mock.Call
}

// RootResource is a helper method to define mock.On call
func (_e *MockQueryDataStore_Expecter) RootResource() *MockQueryDataStore_RootResource_Call {
	return &MockQueryDataStore_RootResource_Call{Call: _e.mock.On("RootResource")}
}

func (_c *MockQueryDataStore_RootResource_Call) Run(run func()) *MockQueryDataStore_RootResource_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockQueryDataStore_RootResource_Call) Return(tableMetadata queryModel.TableMetadata) *MockQueryDataStore_RootResource_Call {
	_c.Call.Return(tableMetadata)
	return _c
}

func (_c *MockQueryDataStore_RootResource_Call) RunAndReturn(run func() queryModel.TableMetadata) *MockQueryDataStore_RootResource_Call {
	_c.Call.Return(run)
	return _c
}

// RootResourceAccessPolicy provides a mock function for the type MockQueryDataStore
func (_mock *MockQueryDataStore) RootResourceAccessPolicy() queryModel.TableAccessPolicy {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for RootResourceAccessPolicy")
	}

	var r0 queryModel.TableAccessPolicy
	if returnFunc, ok := ret.Get(0).(func() queryModel.TableAccessPolicy); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(queryModel.TableAccessPolicy)
		}
	}
	return r0
}

// MockQueryDataStore_RootResourceAccessPolicy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RootResourceAccessPolicy'
type MockQueryDataStore_RootResourceAccessPolicy_Call struct {
	*mock.Call
}

// RootResourceAccessPolicy is a helper method to define mock.On call
func (_e *MockQueryDataStore_Expecter) RootResourceAccessPolicy() *MockQueryDataStore_RootResourceAccessPolicy_Call {
	return &MockQueryDataStore_RootResourceAccessPolicy_Call{Call: _e.mock.On("RootResourceAccessPolicy")}
}

func (_c *MockQueryDataStore_RootResourceAccessPolicy_Call) Run(run func()) *MockQueryDataStore_RootResourceAccessPolicy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockQueryDataStore_RootResourceAccessPolicy_Call) Return(tableAccessPolicy queryModel.TableAccessPolicy) *MockQueryDataStore_RootResourceAccessPolicy_Call {
	_c.Call.Return(tableAccessPolicy)
	return _c
}

func (_c *MockQueryDataStore_RootResourceAccessPolicy_Call) RunAndReturn(run func() queryModel.TableAccessPolicy) *MockQueryDataStore_RootResourceAccessPolicy_Call {
	_c.Call.Return(run)
	return _c
}

// Selects provides a mock function for the type MockQueryDataStore
func (_mock *MockQueryDataStore) Selects() iter.Seq2[string, queryModel.ResolvedColumn] {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Selects")
	}

	var r0 iter.Seq2[string, queryModel.ResolvedColumn]
	if returnFunc, ok := ret.Get(0).(func() iter.Seq2[string, queryModel.ResolvedColumn]); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(iter.Seq2[string, queryModel.ResolvedColumn])
		}
	}
	return r0
}

// MockQueryDataStore_Selects_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Selects'
type MockQueryDataStore_Selects_Call struct {
	*mock.Call
}

// Selects is a helper method to define mock.On call
func (_e *MockQueryDataStore_Expecter) Selects() *MockQueryDataStore_Selects_Call {
	return &MockQueryDataStore_Selects_Call{Call: _e.mock.On("Selects")}
}

func (_c *MockQueryDataStore_Selects_Call) Run(run func()) *MockQueryDataStore_Selects_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockQueryDataStore_Selects_Call) Return(seq2 iter.Seq2[string, queryModel.ResolvedColumn]) *MockQueryDataStore_Selects_Call {
	_c.Call.Return(seq2)
	return _c
}

func (_c *MockQueryDataStore_Selects_Call) RunAndReturn(run func() iter.Seq2[string, queryModel.ResolvedColumn]) *MockQueryDataStore_Selects_Call {
	_c.Call.Return(run)
	return _c
}

// SelectsLen provides a mock function for the type MockQueryDataStore
func (_mock *MockQueryDataStore) SelectsLen() int {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for SelectsLen")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func() int); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// MockQueryDataStore_SelectsLen_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SelectsLen'
type MockQueryDataStore_SelectsLen_Call struct {
	*mock.Call
}

// SelectsLen is a helper method to define mock.On call
func (_e *MockQueryDataStore_Expecter) SelectsLen() *MockQueryDataStore_SelectsLen_Call {
	return &MockQueryDataStore_SelectsLen_Call{Call: _e.mock.On("SelectsLen")}
}

func (_c *MockQueryDataStore_SelectsLen_Call) Run(run func()) *MockQueryDataStore_SelectsLen_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockQueryDataStore_SelectsLen_Call) Return(n int) *MockQueryDataStore_SelectsLen_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockQueryDataStore_SelectsLen_Call) RunAndReturn(run func() int) *MockQueryDataStore_SelectsLen_Call {
	_c.Call.Return(run)
	return _c
}

// SetDoCount provides a mock function for the type MockQueryDataStore
func (_mock *MockQueryDataStore) SetDoCount(doCount bool) {
	_mock.Called(doCount)
	return
}

// MockQueryDataStore_SetDoCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetDoCount'
type MockQueryDataStore_SetDoCount_Call struct {
	*mock.Call
}

// SetDoCount is a helper method to define mock.On call
//   - doCount bool
func (_e *MockQueryDataStore_Expecter) SetDoCount(doCount any) *MockQueryDataStore_SetDoCount_Call {
	return &MockQueryDataStore_SetDoCount_Call{Call: _e.mock.On("SetDoCount", doCount)}
}

func (_c *MockQueryDataStore_SetDoCount_Call) Run(run func(doCount bool)) *MockQueryDataStore_SetDoCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 bool
		if args[0] != nil {
			arg0 = args[0].(bool)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockQueryDataStore_SetDoCount_Call) Return() *MockQueryDataStore_SetDoCount_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockQueryDataStore_SetDoCount_Call) RunAndReturn(run func(doCount bool)) *MockQueryDataStore_SetDoCount_Call {
	_c.Run(run)
	return _c
}

// SetFilterExpression provides a mock function for the type MockQueryDataStore
func (_mock *MockQueryDataStore) SetFilterExpression(ex queryModel.FilterExpression) {
	_mock.Called(ex)
	return
}

// MockQueryDataStore_SetFilterExpression_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetFilterExpression'
type MockQueryDataStore_SetFilterExpression_Call struct {
	*mock.Call
}

// SetFilterExpression is a helper method to define mock.On call
//   - ex queryModel.FilterExpression
func (_e *MockQueryDataStore_Expecter) SetFilterExpression(ex any) *MockQueryDataStore_SetFilterExpression_Call {
	return &MockQueryDataStore_SetFilterExpression_Call{Call: _e.mock.On("SetFilterExpression", ex)}
}

func (_c *MockQueryDataStore_SetFilterExpression_Call) Run(run func(ex queryModel.FilterExpression)) *MockQueryDataStore_SetFilterExpression_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 queryModel.FilterExpression
		if args[0] != nil {
			arg0 = args[0].(queryModel.FilterExpression)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockQueryDataStore_SetFilterExpression_Call) Return() *MockQueryDataStore_SetFilterExpression_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockQueryDataStore_SetFilterExpression_Call) RunAndReturn(run func(ex queryModel.FilterExpression)) *MockQueryDataStore_SetFilterExpression_Call {
	_c.Run(run)
	return _c
}

// SetLimit provides a mock function for the type MockQueryDataStore
func (_mock *MockQueryDataStore) SetLimit(limit int) error {
	ret := _mock.Called(limit)

	if len(ret) == 0 {
		panic("no return value specified for SetLimit")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int) error); ok {
		r0 = returnFunc(limit)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockQueryDataStore_SetLimit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetLimit'
type MockQueryDataStore_SetLimit_Call struct {
	*mock.Call
}

// SetLimit is a helper method to define mock.On call
//   - limit int
func (_e *MockQueryDataStore_Expecter) SetLimit(limit any) *MockQueryDataStore_SetLimit_Call {
	return &MockQueryDataStore_SetLimit_Call{Call: _e.mock.On("SetLimit", limit)}
}

func (_c *MockQueryDataStore_SetLimit_Call) Run(run func(limit int)) *MockQueryDataStore_SetLimit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockQueryDataStore_SetLimit_Call) Return(err error) *MockQueryDataStore_SetLimit_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockQueryDataStore_SetLimit_Call) RunAndReturn(run func(limit int) error) *MockQueryDataStore_SetLimit_Call {
	_c.Call.Return(run)
	return _c
}

// SetPagingToken provides a mock function for the type MockQueryDataStore
func (_mock *MockQueryDataStore) SetPagingToken(s string) {
	_mock.Called(s)
	return
}

// MockQueryDataStore_SetPagingToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetPagingToken'
type MockQueryDataStore_SetPagingToken_Call struct {
	*mock.Call
}

// SetPagingToken is a helper method to define mock.On call
//   - s string
func (_e *MockQueryDataStore_Expecter) SetPagingToken(s any) *MockQueryDataStore_SetPagingToken_Call {
	return &MockQueryDataStore_SetPagingToken_Call{Call: _e.mock.On("SetPagingToken", s)}
}

func (_c *MockQueryDataStore_SetPagingToken_Call) Run(run func(s string)) *MockQueryDataStore_SetPagingToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockQueryDataStore_SetPagingToken_Call) Return() *MockQueryDataStore_SetPagingToken_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockQueryDataStore_SetPagingToken_Call) RunAndReturn(run func(s string)) *MockQueryDataStore_SetPagingToken_Call {
	_c.Run(run)
	return _c
}

// SetSystemLimit provides a mock function for the type MockQueryDataStore
func (_mock *MockQueryDataStore) SetSystemLimit(limit int) error {
	ret := _mock.Called(limit)

	if len(ret) == 0 {
		panic("no return value specified for SetSystemLimit")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int) error); ok {
		r0 = returnFunc(limit)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockQueryDataStore_SetSystemLimit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetSystemLimit'
type MockQueryDataStore_SetSystemLimit_Call struct {
	*mock.Call
}

// SetSystemLimit is a helper method to define mock.On call
//   - limit int
func (_e *MockQueryDataStore_Expecter) SetSystemLimit(limit any) *MockQueryDataStore_SetSystemLimit_Call {
	return &MockQueryDataStore_SetSystemLimit_Call{Call: _e.mock.On("SetSystemLimit", limit)}
}

func (_c *MockQueryDataStore_SetSystemLimit_Call) Run(run func(limit int)) *MockQueryDataStore_SetSystemLimit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockQueryDataStore_SetSystemLimit_Call) Return(err error) *MockQueryDataStore_SetSystemLimit_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockQueryDataStore_SetSystemLimit_Call) RunAndReturn(run func(limit int) error) *MockQueryDataStore_SetSystemLimit_Call {
	_c.Call.Return(run)
	return _c
}

// SystemLimit provides a mock function for the type MockQueryDataStore
func (_mock *MockQueryDataStore) SystemLimit() uint16 {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for SystemLimit")
	}

	var r0 uint16
	if returnFunc, ok := ret.Get(0).(func() uint16); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(uint16)
	}
	return r0
}

// MockQueryDataStore_SystemLimit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SystemLimit'
type MockQueryDataStore_SystemLimit_Call struct {
	*mock.Call
}

// SystemLimit is a helper method to define mock.On call
func (_e *MockQueryDataStore_Expecter) SystemLimit() *MockQueryDataStore_SystemLimit_Call {
	return &MockQueryDataStore_SystemLimit_Call{Call: _e.mock.On("SystemLimit")}
}

func (_c *MockQueryDataStore_SystemLimit_Call) Run(run func()) *MockQueryDataStore_SystemLimit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockQueryDataStore_SystemLimit_Call) Return(v uint16) *MockQueryDataStore_SystemLimit_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *MockQueryDataStore_SystemLimit_Call) RunAndReturn(run func() uint16) *MockQueryDataStore_SystemLimit_Call {
	_c.Call.Return(run)
	return _c
}
