// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package handlers

import (
	"context"
	"io"
	"net/http"

	mock "github.com/stretchr/testify/mock"
	"github.com/turnerbenjamin/heterogen_portal/internal/model"
	"github.com/turnerbenjamin/heterogen_portal/internal/services"
	"github.com/turnerbenjamin/heterogen_portal/internal/templates"
	"github.com/turnerbenjamin/querystack/querymodel"
)

// NewMockJsonSerialiser creates a new instance of MockJsonSerialiser. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockJsonSerialiser(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockJsonSerialiser {
	mock := &MockJsonSerialiser{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockJsonSerialiser is an autogenerated mock type for the JsonSerialiser type
type MockJsonSerialiser struct {
	mock.Mock
}

type MockJsonSerialiser_Expecter struct {
	mock *mock.Mock
}

func (_m *MockJsonSerialiser) EXPECT() *MockJsonSerialiser_Expecter {
	return &MockJsonSerialiser_Expecter{mock: &_m.Mock}
}

// Marshal provides a mock function for the type MockJsonSerialiser
func (_mock *MockJsonSerialiser) Marshal(v any) ([]byte, error) {
	ret := _mock.Called(v)

	if len(ret) == 0 {
		panic("no return value specified for Marshal")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(any) ([]byte, error)); ok {
		return returnFunc(v)
	}
	if returnFunc, ok := ret.Get(0).(func(any) []byte); ok {
		r0 = returnFunc(v)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(any) error); ok {
		r1 = returnFunc(v)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockJsonSerialiser_Marshal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Marshal'
type MockJsonSerialiser_Marshal_Call struct {
	*mock.Call
}

// Marshal is a helper method to define mock.On call
//   - v any
func (_e *MockJsonSerialiser_Expecter) Marshal(v any) *MockJsonSerialiser_Marshal_Call {
	return &MockJsonSerialiser_Marshal_Call{Call: _e.mock.On("Marshal", v)}
}

func (_c *MockJsonSerialiser_Marshal_Call) Run(run func(v any)) *MockJsonSerialiser_Marshal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 any
		if args[0] != nil {
			arg0 = args[0].(any)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockJsonSerialiser_Marshal_Call) Return(bytes []byte, err error) *MockJsonSerialiser_Marshal_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockJsonSerialiser_Marshal_Call) RunAndReturn(run func(v any) ([]byte, error)) *MockJsonSerialiser_Marshal_Call {
	_c.Call.Return(run)
	return _c
}

// Unmarshal provides a mock function for the type MockJsonSerialiser
func (_mock *MockJsonSerialiser) Unmarshal(data []byte, v any) error {
	ret := _mock.Called(data, v)

	if len(ret) == 0 {
		panic("no return value specified for Unmarshal")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func([]byte, any) error); ok {
		r0 = returnFunc(data, v)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockJsonSerialiser_Unmarshal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unmarshal'
type MockJsonSerialiser_Unmarshal_Call struct {
	*mock.Call
}

// Unmarshal is a helper method to define mock.On call
//   - data []byte
//   - v any
func (_e *MockJsonSerialiser_Expecter) Unmarshal(data any, v any) *MockJsonSerialiser_Unmarshal_Call {
	return &MockJsonSerialiser_Unmarshal_Call{Call: _e.mock.On("Unmarshal", data, v)}
}

func (_c *MockJsonSerialiser_Unmarshal_Call) Run(run func(data []byte, v any)) *MockJsonSerialiser_Unmarshal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		var arg1 any
		if args[1] != nil {
			arg1 = args[1].(any)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockJsonSerialiser_Unmarshal_Call) Return(err error) *MockJsonSerialiser_Unmarshal_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockJsonSerialiser_Unmarshal_Call) RunAndReturn(run func(data []byte, v any) error) *MockJsonSerialiser_Unmarshal_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuthService creates a new instance of MockAuthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthService {
	mock := &MockAuthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuthService is an autogenerated mock type for the AuthService type
type MockAuthService struct {
	mock.Mock
}

type MockAuthService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthService) EXPECT() *MockAuthService_Expecter {
	return &MockAuthService_Expecter{mock: &_m.Mock}
}

// AuthenticateUser provides a mock function for the type MockAuthService
func (_mock *MockAuthService) AuthenticateUser(ctx context.Context, authorisationCode string, returnedState string, signedOidcState string) (*services.AuthenticateUserResponse, error) {
	ret := _mock.Called(ctx, authorisationCode, returnedState, signedOidcState)

	if len(ret) == 0 {
		panic("no return value specified for AuthenticateUser")
	}

	var r0 *services.AuthenticateUserResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (*services.AuthenticateUserResponse, error)); ok {
		return returnFunc(ctx, authorisationCode, returnedState, signedOidcState)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) *services.AuthenticateUserResponse); ok {
		r0 = returnFunc(ctx, authorisationCode, returnedState, signedOidcState)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*services.AuthenticateUserResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, authorisationCode, returnedState, signedOidcState)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthService_AuthenticateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AuthenticateUser'
type MockAuthService_AuthenticateUser_Call struct {
	*mock.Call
}

// AuthenticateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - authorisationCode string
//   - returnedState string
//   - signedOidcState string
func (_e *MockAuthService_Expecter) AuthenticateUser(ctx any, authorisationCode any, returnedState any, signedOidcState any) *MockAuthService_AuthenticateUser_Call {
	return &MockAuthService_AuthenticateUser_Call{Call: _e.mock.On("AuthenticateUser", ctx, authorisationCode, returnedState, signedOidcState)}
}

func (_c *MockAuthService_AuthenticateUser_Call) Run(run func(ctx context.Context, authorisationCode string, returnedState string, signedOidcState string)) *MockAuthService_AuthenticateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockAuthService_AuthenticateUser_Call) Return(resp *services.AuthenticateUserResponse, err error) *MockAuthService_AuthenticateUser_Call {
	_c.Call.Return(resp, err)
	return _c
}

func (_c *MockAuthService_AuthenticateUser_Call) RunAndReturn(run func(ctx context.Context, authorisationCode string, returnedState string, signedOidcState string) (*services.AuthenticateUserResponse, error)) *MockAuthService_AuthenticateUser_Call {
	_c.Call.Return(run)
	return _c
}

// BuildSignInRedirectRequest provides a mock function for the type MockAuthService
func (_mock *MockAuthService) BuildSignInRedirectRequest(requestedPath string) (*services.SignInRedirectRequest, error) {
	ret := _mock.Called(requestedPath)

	if len(ret) == 0 {
		panic("no return value specified for BuildSignInRedirectRequest")
	}

	var r0 *services.SignInRedirectRequest
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*services.SignInRedirectRequest, error)); ok {
		return returnFunc(requestedPath)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *services.SignInRedirectRequest); ok {
		r0 = returnFunc(requestedPath)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*services.SignInRedirectRequest)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(requestedPath)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthService_BuildSignInRedirectRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BuildSignInRedirectRequest'
type MockAuthService_BuildSignInRedirectRequest_Call struct {
	*mock.Call
}

// BuildSignInRedirectRequest is a helper method to define mock.On call
//   - requestedPath string
func (_e *MockAuthService_Expecter) BuildSignInRedirectRequest(requestedPath any) *MockAuthService_BuildSignInRedirectRequest_Call {
	return &MockAuthService_BuildSignInRedirectRequest_Call{Call: _e.mock.On("BuildSignInRedirectRequest", requestedPath)}
}

func (_c *MockAuthService_BuildSignInRedirectRequest_Call) Run(run func(requestedPath string)) *MockAuthService_BuildSignInRedirectRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAuthService_BuildSignInRedirectRequest_Call) Return(signInRedirectRequest *services.SignInRedirectRequest, err error) *MockAuthService_BuildSignInRedirectRequest_Call {
	_c.Call.Return(signInRedirectRequest, err)
	return _c
}

func (_c *MockAuthService_BuildSignInRedirectRequest_Call) RunAndReturn(run func(requestedPath string) (*services.SignInRedirectRequest, error)) *MockAuthService_BuildSignInRedirectRequest_Call {
	_c.Call.Return(run)
	return _c
}

// BuildSignOutRedirectRequest provides a mock function for the type MockAuthService
func (_mock *MockAuthService) BuildSignOutRedirectRequest() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for BuildSignOutRedirectRequest")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockAuthService_BuildSignOutRedirectRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BuildSignOutRedirectRequest'
type MockAuthService_BuildSignOutRedirectRequest_Call struct {
	*mock.Call
}

// BuildSignOutRedirectRequest is a helper method to define mock.On call
func (_e *MockAuthService_Expecter) BuildSignOutRedirectRequest() *MockAuthService_BuildSignOutRedirectRequest_Call {
	return &MockAuthService_BuildSignOutRedirectRequest_Call{Call: _e.mock.On("BuildSignOutRedirectRequest")}
}

func (_c *MockAuthService_BuildSignOutRedirectRequest_Call) Run(run func()) *MockAuthService_BuildSignOutRedirectRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAuthService_BuildSignOutRedirectRequest_Call) Return(s string) *MockAuthService_BuildSignOutRedirectRequest_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockAuthService_BuildSignOutRedirectRequest_Call) RunAndReturn(run func() string) *MockAuthService_BuildSignOutRedirectRequest_Call {
	_c.Call.Return(run)
	return _c
}

// ParseUserJwtCookie provides a mock function for the type MockAuthService
func (_mock *MockAuthService) ParseUserJwtCookie(tokenString string) (*services.AppClaims, error) {
	ret := _mock.Called(tokenString)

	if len(ret) == 0 {
		panic("no return value specified for ParseUserJwtCookie")
	}

	var r0 *services.AppClaims
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*services.AppClaims, error)); ok {
		return returnFunc(tokenString)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *services.AppClaims); ok {
		r0 = returnFunc(tokenString)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*services.AppClaims)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(tokenString)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthService_ParseUserJwtCookie_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ParseUserJwtCookie'
type MockAuthService_ParseUserJwtCookie_Call struct {
	*mock.Call
}

// ParseUserJwtCookie is a helper method to define mock.On call
//   - tokenString string
func (_e *MockAuthService_Expecter) ParseUserJwtCookie(tokenString any) *MockAuthService_ParseUserJwtCookie_Call {
	return &MockAuthService_ParseUserJwtCookie_Call{Call: _e.mock.On("ParseUserJwtCookie", tokenString)}
}

func (_c *MockAuthService_ParseUserJwtCookie_Call) Run(run func(tokenString string)) *MockAuthService_ParseUserJwtCookie_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAuthService_ParseUserJwtCookie_Call) Return(appClaims *services.AppClaims, err error) *MockAuthService_ParseUserJwtCookie_Call {
	_c.Call.Return(appClaims, err)
	return _c
}

func (_c *MockAuthService_ParseUserJwtCookie_Call) RunAndReturn(run func(tokenString string) (*services.AppClaims, error)) *MockAuthService_ParseUserJwtCookie_Call {
	_c.Call.Return(run)
	return _c
}

// RetrieveUserById provides a mock function for the type MockAuthService
func (_mock *MockAuthService) RetrieveUserById(userId string) (*model.UsersModel, error) {
	ret := _mock.Called(userId)

	if len(ret) == 0 {
		panic("no return value specified for RetrieveUserById")
	}

	var r0 *model.UsersModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*model.UsersModel, error)); ok {
		return returnFunc(userId)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *model.UsersModel); ok {
		r0 = returnFunc(userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UsersModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(userId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthService_RetrieveUserById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RetrieveUserById'
type MockAuthService_RetrieveUserById_Call struct {
	*mock.Call
}

// RetrieveUserById is a helper method to define mock.On call
//   - userId string
func (_e *MockAuthService_Expecter) RetrieveUserById(userId any) *MockAuthService_RetrieveUserById_Call {
	return &MockAuthService_RetrieveUserById_Call{Call: _e.mock.On("RetrieveUserById", userId)}
}

func (_c *MockAuthService_RetrieveUserById_Call) Run(run func(userId string)) *MockAuthService_RetrieveUserById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAuthService_RetrieveUserById_Call) Return(usersModel *model.UsersModel, err error) *MockAuthService_RetrieveUserById_Call {
	_c.Call.Return(usersModel, err)
	return _c
}

func (_c *MockAuthService_RetrieveUserById_Call) RunAndReturn(run func(userId string) (*model.UsersModel, error)) *MockAuthService_RetrieveUserById_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockErrorWriter creates a new instance of MockErrorWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockErrorWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockErrorWriter {
	mock := &MockErrorWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockErrorWriter is an autogenerated mock type for the ErrorWriter type
type MockErrorWriter struct {
	mock.Mock
}

type MockErrorWriter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockErrorWriter) EXPECT() *MockErrorWriter_Expecter {
	return &MockErrorWriter_Expecter{mock: &_m.Mock}
}

// Write provides a mock function for the type MockErrorWriter
func (_mock *MockErrorWriter) Write(responseWriter http.ResponseWriter, request *http.Request, appError *AppError) error {
	ret := _mock.Called(responseWriter, request, appError)

	if len(ret) == 0 {
		panic("no return value specified for Write")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(http.ResponseWriter, *http.Request, *AppError) error); ok {
		r0 = returnFunc(responseWriter, request, appError)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockErrorWriter_Write_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Write'
type MockErrorWriter_Write_Call struct {
	*mock.Call
}

// Write is a helper method to define mock.On call
//   - responseWriter http.ResponseWriter
//   - request *http.Request
//   - appError *AppError
func (_e *MockErrorWriter_Expecter) Write(responseWriter any, request any, appError any) *MockErrorWriter_Write_Call {
	return &MockErrorWriter_Write_Call{Call: _e.mock.On("Write", responseWriter, request, appError)}
}

func (_c *MockErrorWriter_Write_Call) Run(run func(responseWriter http.ResponseWriter, request *http.Request, appError *AppError)) *MockErrorWriter_Write_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		var arg2 *AppError
		if args[2] != nil {
			arg2 = args[2].(*AppError)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockErrorWriter_Write_Call) Return(err error) *MockErrorWriter_Write_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockErrorWriter_Write_Call) RunAndReturn(run func(responseWriter http.ResponseWriter, request *http.Request, appError *AppError) error) *MockErrorWriter_Write_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserState creates a new instance of MockUserState. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserState(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserState {
	mock := &MockUserState{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserState is an autogenerated mock type for the UserState type
type MockUserState struct {
	mock.Mock
}

type MockUserState_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserState) EXPECT() *MockUserState_Expecter {
	return &MockUserState_Expecter{mock: &_m.Mock}
}

// GetUser provides a mock function for the type MockUserState
func (_mock *MockUserState) GetUser() *model.UsersModel {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetUser")
	}

	var r0 *model.UsersModel
	if returnFunc, ok := ret.Get(0).(func() *model.UsersModel); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UsersModel)
		}
	}
	return r0
}

// MockUserState_GetUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUser'
type MockUserState_GetUser_Call struct {
	*mock.Call
}

// GetUser is a helper method to define mock.On call
func (_e *MockUserState_Expecter) GetUser() *MockUserState_GetUser_Call {
	return &MockUserState_GetUser_Call{Call: _e.mock.On("GetUser")}
}

func (_c *MockUserState_GetUser_Call) Run(run func()) *MockUserState_GetUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUserState_GetUser_Call) Return(usersModel *model.UsersModel) *MockUserState_GetUser_Call {
	_c.Call.Return(usersModel)
	return _c
}

func (_c *MockUserState_GetUser_Call) RunAndReturn(run func() *model.UsersModel) *MockUserState_GetUser_Call {
	_c.Call.Return(run)
	return _c
}

// SetUser provides a mock function for the type MockUserState
func (_mock *MockUserState) SetUser(v *model.UsersModel) {
	_mock.Called(v)
	return
}

// MockUserState_SetUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetUser'
type MockUserState_SetUser_Call struct {
	*mock.Call
}

// SetUser is a helper method to define mock.On call
//   - v *model.UsersModel
func (_e *MockUserState_Expecter) SetUser(v any) *MockUserState_SetUser_Call {
	return &MockUserState_SetUser_Call{Call: _e.mock.On("SetUser", v)}
}

func (_c *MockUserState_SetUser_Call) Run(run func(v *model.UsersModel)) *MockUserState_SetUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *model.UsersModel
		if args[0] != nil {
			arg0 = args[0].(*model.UsersModel)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUserState_SetUser_Call) Return() *MockUserState_SetUser_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockUserState_SetUser_Call) RunAndReturn(run func(v *model.UsersModel)) *MockUserState_SetUser_Call {
	_c.Run(run)
	return _c
}

// NewMockQueryService creates a new instance of MockQueryService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQueryService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQueryService {
	mock := &MockQueryService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockQueryService is an autogenerated mock type for the QueryService type
type MockQueryService struct {
	mock.Mock
}

type MockQueryService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQueryService) EXPECT() *MockQueryService_Expecter {
	return &MockQueryService_Expecter{mock: &_m.Mock}
}

// ExecuteQuery provides a mock function for the type MockQueryService
func (_mock *MockQueryService) ExecuteQuery(ctx context.Context, resource string, queryString string) (*querymodel.ExecuteResult, error) {
	ret := _mock.Called(ctx, resource, queryString)

	if len(ret) == 0 {
		panic("no return value specified for ExecuteQuery")
	}

	var r0 *querymodel.ExecuteResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*querymodel.ExecuteResult, error)); ok {
		return returnFunc(ctx, resource, queryString)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *querymodel.ExecuteResult); ok {
		r0 = returnFunc(ctx, resource, queryString)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*querymodel.ExecuteResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, resource, queryString)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQueryService_ExecuteQuery_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecuteQuery'
type MockQueryService_ExecuteQuery_Call struct {
	*mock.Call
}

// ExecuteQuery is a helper method to define mock.On call
//   - ctx context.Context
//   - resource string
//   - queryString string
func (_e *MockQueryService_Expecter) ExecuteQuery(ctx any, resource any, queryString any) *MockQueryService_ExecuteQuery_Call {
	return &MockQueryService_ExecuteQuery_Call{Call: _e.mock.On("ExecuteQuery", ctx, resource, queryString)}
}

func (_c *MockQueryService_ExecuteQuery_Call) Run(run func(ctx context.Context, resource string, queryString string)) *MockQueryService_ExecuteQuery_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockQueryService_ExecuteQuery_Call) Return(executeResult *querymodel.ExecuteResult, err error) *MockQueryService_ExecuteQuery_Call {
	_c.Call.Return(executeResult, err)
	return _c
}

func (_c *MockQueryService_ExecuteQuery_Call) RunAndReturn(run func(ctx context.Context, resource string, queryString string) (*querymodel.ExecuteResult, error)) *MockQueryService_ExecuteQuery_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTemplateStore creates a new instance of MockTemplateStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTemplateStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTemplateStore {
	mock := &MockTemplateStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTemplateStore is an autogenerated mock type for the TemplateStore type
type MockTemplateStore struct {
	mock.Mock
}

type MockTemplateStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTemplateStore) EXPECT() *MockTemplateStore_Expecter {
	return &MockTemplateStore_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type MockTemplateStore
func (_mock *MockTemplateStore) Execute(id templates.TemplateIdentifier, w io.Writer, data templates.TemplateArgs) error {
	ret := _mock.Called(id, w, data)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(templates.TemplateIdentifier, io.Writer, templates.TemplateArgs) error); ok {
		r0 = returnFunc(id, w, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTemplateStore_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockTemplateStore_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - id templates.TemplateIdentifier
//   - w io.Writer
//   - data templates.TemplateArgs
func (_e *MockTemplateStore_Expecter) Execute(id any, w any, data any) *MockTemplateStore_Execute_Call {
	return &MockTemplateStore_Execute_Call{Call: _e.mock.On("Execute", id, w, data)}
}

func (_c *MockTemplateStore_Execute_Call) Run(run func(id templates.TemplateIdentifier, w io.Writer, data templates.TemplateArgs)) *MockTemplateStore_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 templates.TemplateIdentifier
		if args[0] != nil {
			arg0 = args[0].(templates.TemplateIdentifier)
		}
		var arg1 io.Writer
		if args[1] != nil {
			arg1 = args[1].(io.Writer)
		}
		var arg2 templates.TemplateArgs
		if args[2] != nil {
			arg2 = args[2].(templates.TemplateArgs)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTemplateStore_Execute_Call) Return(err error) *MockTemplateStore_Execute_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTemplateStore_Execute_Call) RunAndReturn(run func(id templates.TemplateIdentifier, w io.Writer, data templates.TemplateArgs) error) *MockTemplateStore_Execute_Call {
	_c.Call.Return(run)
	return _c
}
