// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package db

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockCrypt creates a new instance of MockCrypt. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCrypt(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCrypt {
	mock := &MockCrypt{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCrypt is an autogenerated mock type for the Crypt type
type MockCrypt struct {
	mock.Mock
}

type MockCrypt_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCrypt) EXPECT() *MockCrypt_Expecter {
	return &MockCrypt_Expecter{mock: &_m.Mock}
}

// CompareHashAndPassword provides a mock function for the type MockCrypt
func (_mock *MockCrypt) CompareHashAndPassword(hashed []byte, password []byte) error {
	ret := _mock.Called(hashed, password)

	if len(ret) == 0 {
		panic("no return value specified for CompareHashAndPassword")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func([]byte, []byte) error); ok {
		r0 = returnFunc(hashed, password)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCrypt_CompareHashAndPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CompareHashAndPassword'
type MockCrypt_CompareHashAndPassword_Call struct {
	*mock.Call
}

// CompareHashAndPassword is a helper method to define mock.On call
//   - hashed []byte
//   - password []byte
func (_e *MockCrypt_Expecter) CompareHashAndPassword(hashed any, password any) *MockCrypt_CompareHashAndPassword_Call {
	return &MockCrypt_CompareHashAndPassword_Call{Call: _e.mock.On("CompareHashAndPassword", hashed, password)}
}

func (_c *MockCrypt_CompareHashAndPassword_Call) Run(run func(hashed []byte, password []byte)) *MockCrypt_CompareHashAndPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCrypt_CompareHashAndPassword_Call) Return(err error) *MockCrypt_CompareHashAndPassword_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCrypt_CompareHashAndPassword_Call) RunAndReturn(run func(hashed []byte, password []byte) error) *MockCrypt_CompareHashAndPassword_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateFromPassword provides a mock function for the type MockCrypt
func (_mock *MockCrypt) GenerateFromPassword(password []byte, cost int) ([]byte, error) {
	ret := _mock.Called(password, cost)

	if len(ret) == 0 {
		panic("no return value specified for GenerateFromPassword")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]byte, int) ([]byte, error)); ok {
		return returnFunc(password, cost)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte, int) []byte); ok {
		r0 = returnFunc(password, cost)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]byte, int) error); ok {
		r1 = returnFunc(password, cost)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCrypt_GenerateFromPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateFromPassword'
type MockCrypt_GenerateFromPassword_Call struct {
	*mock.Call
}

// GenerateFromPassword is a helper method to define mock.On call
//   - password []byte
//   - cost int
func (_e *MockCrypt_Expecter) GenerateFromPassword(password any, cost any) *MockCrypt_GenerateFromPassword_Call {
	return &MockCrypt_GenerateFromPassword_Call{Call: _e.mock.On("GenerateFromPassword", password, cost)}
}

func (_c *MockCrypt_GenerateFromPassword_Call) Run(run func(password []byte, cost int)) *MockCrypt_GenerateFromPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCrypt_GenerateFromPassword_Call) Return(bytes []byte, err error) *MockCrypt_GenerateFromPassword_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockCrypt_GenerateFromPassword_Call) RunAndReturn(run func(password []byte, cost int) ([]byte, error)) *MockCrypt_GenerateFromPassword_Call {
	_c.Call.Return(run)
	return _c
}
