// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package paginationTokens

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockPayloadSigner creates a new instance of MockPayloadSigner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPayloadSigner(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPayloadSigner {
	mock := &MockPayloadSigner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPayloadSigner is an autogenerated mock type for the PayloadSigner type
type MockPayloadSigner struct {
	mock.Mock
}

type MockPayloadSigner_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPayloadSigner) EXPECT() *MockPayloadSigner_Expecter {
	return &MockPayloadSigner_Expecter{mock: &_m.Mock}
}

// Sign provides a mock function for the type MockPayloadSigner
func (_mock *MockPayloadSigner) Sign(secret []byte, data []byte) string {
	ret := _mock.Called(secret, data)

	if len(ret) == 0 {
		panic("no return value specified for Sign")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func([]byte, []byte) string); ok {
		r0 = returnFunc(secret, data)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockPayloadSigner_Sign_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Sign'
type MockPayloadSigner_Sign_Call struct {
	*mock.Call
}

// Sign is a helper method to define mock.On call
//   - secret []byte
//   - data []byte
func (_e *MockPayloadSigner_Expecter) Sign(secret any, data any) *MockPayloadSigner_Sign_Call {
	return &MockPayloadSigner_Sign_Call{Call: _e.mock.On("Sign", secret, data)}
}

func (_c *MockPayloadSigner_Sign_Call) Run(run func(secret []byte, data []byte)) *MockPayloadSigner_Sign_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPayloadSigner_Sign_Call) Return(s string) *MockPayloadSigner_Sign_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockPayloadSigner_Sign_Call) RunAndReturn(run func(secret []byte, data []byte) string) *MockPayloadSigner_Sign_Call {
	_c.Call.Return(run)
	return _c
}

// Verify provides a mock function for the type MockPayloadSigner
func (_mock *MockPayloadSigner) Verify(secret []byte, value string) ([]byte, bool) {
	ret := _mock.Called(secret, value)

	if len(ret) == 0 {
		panic("no return value specified for Verify")
	}

	var r0 []byte
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func([]byte, string) ([]byte, bool)); ok {
		return returnFunc(secret, value)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte, string) []byte); ok {
		r0 = returnFunc(secret, value)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]byte, string) bool); ok {
		r1 = returnFunc(secret, value)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// MockPayloadSigner_Verify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Verify'
type MockPayloadSigner_Verify_Call struct {
	*mock.Call
}

// Verify is a helper method to define mock.On call
//   - secret []byte
//   - value string
func (_e *MockPayloadSigner_Expecter) Verify(secret any, value any) *MockPayloadSigner_Verify_Call {
	return &MockPayloadSigner_Verify_Call{Call: _e.mock.On("Verify", secret, value)}
}

func (_c *MockPayloadSigner_Verify_Call) Run(run func(secret []byte, value string)) *MockPayloadSigner_Verify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPayloadSigner_Verify_Call) Return(data []byte, ok bool) *MockPayloadSigner_Verify_Call {
	_c.Call.Return(data, ok)
	return _c
}

func (_c *MockPayloadSigner_Verify_Call) RunAndReturn(run func(secret []byte, value string) ([]byte, bool)) *MockPayloadSigner_Verify_Call {
	_c.Call.Return(run)
	return _c
}
