// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package queryExecutor

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// ExecuteJsonRequest provides a mock function for the type MockRepository
func (_mock *MockRepository) ExecuteJsonRequest(ctx context.Context, queryStatementStr string, args []any) ([]byte, error) {
	ret := _mock.Called(ctx, queryStatementStr, args)

	if len(ret) == 0 {
		panic("no return value specified for ExecuteJsonRequest")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []any) ([]byte, error)); ok {
		return returnFunc(ctx, queryStatementStr, args)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []any) []byte); ok {
		r0 = returnFunc(ctx, queryStatementStr, args)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, []any) error); ok {
		r1 = returnFunc(ctx, queryStatementStr, args)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_ExecuteJsonRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecuteJsonRequest'
type MockRepository_ExecuteJsonRequest_Call struct {
	*mock.Call
}

// ExecuteJsonRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - queryStatementStr string
//   - args []any
func (_e *MockRepository_Expecter) ExecuteJsonRequest(ctx any, queryStatementStr any, args any) *MockRepository_ExecuteJsonRequest_Call {
	return &MockRepository_ExecuteJsonRequest_Call{Call: _e.mock.On("ExecuteJsonRequest", ctx, queryStatementStr, args)}
}

func (_c *MockRepository_ExecuteJsonRequest_Call) Run(run func(ctx context.Context, queryStatementStr string, args []any)) *MockRepository_ExecuteJsonRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []any
		if args[2] != nil {
			arg2 = args[2].([]any)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_ExecuteJsonRequest_Call) Return(bytes []byte, err error) *MockRepository_ExecuteJsonRequest_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockRepository_ExecuteJsonRequest_Call) RunAndReturn(run func(ctx context.Context, queryStatementStr string, args []any) ([]byte, error)) *MockRepository_ExecuteJsonRequest_Call {
	_c.Call.Return(run)
	return _c
}

// ExecuteJsonRequestWithCount provides a mock function for the type MockRepository
func (_mock *MockRepository) ExecuteJsonRequestWithCount(ctx context.Context, queryStatementStr string, countStatementStr string, sharedArgs []any) ([]byte, *int64, error) {
	ret := _mock.Called(ctx, queryStatementStr, countStatementStr, sharedArgs)

	if len(ret) == 0 {
		panic("no return value specified for ExecuteJsonRequestWithCount")
	}

	var r0 []byte
	var r1 *int64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, []any) ([]byte, *int64, error)); ok {
		return returnFunc(ctx, queryStatementStr, countStatementStr, sharedArgs)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, []any) []byte); ok {
		r0 = returnFunc(ctx, queryStatementStr, countStatementStr, sharedArgs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, []any) *int64); ok {
		r1 = returnFunc(ctx, queryStatementStr, countStatementStr, sharedArgs)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*int64)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string, []any) error); ok {
		r2 = returnFunc(ctx, queryStatementStr, countStatementStr, sharedArgs)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockRepository_ExecuteJsonRequestWithCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecuteJsonRequestWithCount'
type MockRepository_ExecuteJsonRequestWithCount_Call struct {
	*mock.Call
}

// ExecuteJsonRequestWithCount is a helper method to define mock.On call
//   - ctx context.Context
//   - queryStatementStr string
//   - countStatementStr string
//   - sharedArgs []any
func (_e *MockRepository_Expecter) ExecuteJsonRequestWithCount(ctx any, queryStatementStr any, countStatementStr any, sharedArgs any) *MockRepository_ExecuteJsonRequestWithCount_Call {
	return &MockRepository_ExecuteJsonRequestWithCount_Call{Call: _e.mock.On("ExecuteJsonRequestWithCount", ctx, queryStatementStr, countStatementStr, sharedArgs)}
}

func (_c *MockRepository_ExecuteJsonRequestWithCount_Call) Run(run func(ctx context.Context, queryStatementStr string, countStatementStr string, sharedArgs []any)) *MockRepository_ExecuteJsonRequestWithCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []any
		if args[3] != nil {
			arg3 = args[3].([]any)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockRepository_ExecuteJsonRequestWithCount_Call) Return(bytes []byte, n *int64, err error) *MockRepository_ExecuteJsonRequestWithCount_Call {
	_c.Call.Return(bytes, n, err)
	return _c
}

func (_c *MockRepository_ExecuteJsonRequestWithCount_Call) RunAndReturn(run func(ctx context.Context, queryStatementStr string, countStatementStr string, sharedArgs []any) ([]byte, *int64, error)) *MockRepository_ExecuteJsonRequestWithCount_Call {
	_c.Call.Return(run)
	return _c
}
